prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/shared_components/navigation/lists/navigation_bar.sql
@@application/shared_components/navigation/lists/mobile_navigation_menu.sql
@@application/shared_components/navigation/lists/navigation_menu.sql
@@application/shared_components/navigation/lists/event_actions.sql
@@application/shared_components/navigation/lists/preferences.sql
@@application/shared_components/navigation/lists/access_control.sql
@@application/shared_components/navigation/lists/administration.sql
@@application/shared_components/navigation/lists/activity_reporting.sql
@@application/shared_components/navigation/lists/admin_email_groups.sql
@@application/shared_components/files/gc_apxcolor_js.sql
@@application/shared_components/files/group_cal_logo2_png.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/security/authorizations/application_sentry.sql
@@application/shared_components/security/authorizations/contribution_rights.sql
@@application/shared_components/security/authorizations/is_admin.sql
@@application/shared_components/security/app_access_control/contributer.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_processes/default_time_zone.sql
@@application/shared_components/logic/application_processes/clear_create_member_collections.sql
@@application/shared_components/logic/application_processes/trim_all_page_items.sql
@@application/shared_components/logic/application_items/application_title.sql
@@application/shared_components/logic/application_items/calendars_filter.sql
@@application/shared_components/logic/application_items/cals_restricted_to.sql
@@application/shared_components/logic/application_items/contact_email.sql
@@application/shared_components/logic/application_items/event_types_filter.sql
@@application/shared_components/logic/application_items/external_internal_bo.sql
@@application/shared_components/logic/application_items/external_internal_bo_name.sql
@@application/shared_components/logic/application_items/f855_timezone.sql
@@application/shared_components/logic/application_items/host_url.sql
@@application/shared_components/logic/application_items/last_view.sql
@@application/shared_components/logic/application_items/multiple_cal_bo.sql
@@application/shared_components/logic/application_items/multiple_cal_bo_name.sql
@@application/shared_components/logic/application_computations/application_title.sql
@@application/shared_components/logic/application_computations/external_internal_bo.sql
@@application/shared_components/logic/application_computations/external_internal_bo_002.sql
@@application/shared_components/logic/application_computations/external_internal_bo_name.sql
@@application/shared_components/logic/application_computations/multiple_cal_bo_name.sql
@@application/shared_components/logic/application_computations/multiple_cal_bo.sql
@@application/shared_components/logic/application_computations/multiple_cal_bo_002.sql
@@application/shared_components/logic/application_computations/cals_restricted_to.sql
@@application/shared_components/logic/application_computations/host_url.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/access_control_scope.sql
@@application/shared_components/user_interface/lovs/access_control_scope1.sql
@@application/shared_components/user_interface/lovs/access_level.sql
@@application/shared_components/user_interface/lovs/calendars.sql
@@application/shared_components/user_interface/lovs/calendars_full_name.sql
@@application/shared_components/user_interface/lovs/calendars_with_default.sql
@@application/shared_components/user_interface/lovs/checkbox.sql
@@application/shared_components/user_interface/lovs/color_preference.sql
@@application/shared_components/user_interface/lovs/contacts.sql
@@application/shared_components/user_interface/lovs/email_groups.sql
@@application/shared_components/user_interface/lovs/email_groups_with_cnt.sql
@@application/shared_components/user_interface/lovs/event_types.sql
@@application/shared_components/user_interface/lovs/event_types_for_main_cal.sql
@@application/shared_components/user_interface/lovs/events.sql
@@application/shared_components/user_interface/lovs/notification_type.sql
@@application/shared_components/user_interface/lovs/recur_frequency.sql
@@application/shared_components/user_interface/lovs/rows.sql
@@application/shared_components/user_interface/lovs/start_time_selector.sql
@@application/shared_components/user_interface/lovs/std_time_zones.sql
@@application/shared_components/user_interface/lovs/timeframes_for_ir_col_headings.sql
@@application/shared_components/user_interface/lovs/timeframes_showing_dates.sql
@@application/shared_components/user_interface/lovs/timezones.sql
@@application/shared_components/user_interface/lovs/upd_request_af.sql
@@application/shared_components/user_interface/lovs/upd_request_afo.sql
@@application/shared_components/user_interface/lovs/upd_request_fo.sql
@@application/shared_components/user_interface/lovs/username_format.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/page/left_side_column.sql
@@application/shared_components/user_interface/templates/page/left_and_right_side_columns.sql
@@application/shared_components/user_interface/templates/page/login.sql
@@application/shared_components/user_interface/templates/page/master_detail.sql
@@application/shared_components/user_interface/templates/page/minimal_no_navigation.sql
@@application/shared_components/user_interface/templates/page/modal_dialog.sql
@@application/shared_components/user_interface/templates/page/right_side_column.sql
@@application/shared_components/user_interface/templates/page/standard.sql
@@application/shared_components/user_interface/templates/page/wizard_modal_dialog.sql
@@application/shared_components/user_interface/templates/button/standard_button.sql
@@application/shared_components/user_interface/templates/button/icon.sql
@@application/shared_components/user_interface/templates/button/text_with_icon.sql
@@application/shared_components/user_interface/templates/button/text.sql
@@application/shared_components/user_interface/templates/region/inline_popup.sql
@@application/shared_components/user_interface/templates/region/cards_container.sql
@@application/shared_components/user_interface/templates/region/content_block.sql
@@application/shared_components/user_interface/templates/region/footer_toolbar_fixed.sql
@@application/shared_components/user_interface/templates/region/alert.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes.sql
@@application/shared_components/user_interface/templates/region/buttons_container.sql
@@application/shared_components/user_interface/templates/region/carousel_container.sql
@@application/shared_components/user_interface/templates/region/hero.sql
@@application/shared_components/user_interface/templates/region/collapsible.sql
@@application/shared_components/user_interface/templates/region/interactive_report.sql
@@application/shared_components/user_interface/templates/region/login.sql
@@application/shared_components/user_interface/templates/region/inline_dialog.sql
@@application/shared_components/user_interface/templates/region/standard.sql
@@application/shared_components/user_interface/templates/region/title_bar.sql
@@application/shared_components/user_interface/templates/region/wizard_container.sql
@@application/shared_components/user_interface/templates/region/tabs_container.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes_no_grid.sql
@@application/shared_components/user_interface/templates/list/top_navigation_tabs.sql
@@application/shared_components/user_interface/templates/list/top_navigation_mega_menu.sql
@@application/shared_components/user_interface/templates/list/badge_list.sql
@@application/shared_components/user_interface/templates/list/cards.sql
@@application/shared_components/user_interface/templates/list/links_list.sql
@@application/shared_components/user_interface/templates/list/media_list.sql
@@application/shared_components/user_interface/templates/list/menu_bar.sql
@@application/shared_components/user_interface/templates/list/top_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/navigation_bar.sql
@@application/shared_components/user_interface/templates/list/side_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/wizard_progress.sql
@@application/shared_components/user_interface/templates/list/tabs.sql
@@application/shared_components/user_interface/templates/list/menu_popup.sql
@@application/shared_components/user_interface/templates/report/media_list.sql
@@application/shared_components/user_interface/templates/report/timeline.sql
@@application/shared_components/user_interface/templates/report/content_row.sql
@@application/shared_components/user_interface/templates/report/contextual_info.sql
@@application/shared_components/user_interface/templates/report/alerts.sql
@@application/shared_components/user_interface/templates/report/badge_list.sql
@@application/shared_components/user_interface/templates/report/cards.sql
@@application/shared_components/user_interface/templates/report/comments.sql
@@application/shared_components/user_interface/templates/report/search_results.sql
@@application/shared_components/user_interface/templates/report/standard.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_column.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_row.sql
@@application/shared_components/user_interface/templates/label/required_floating.sql
@@application/shared_components/user_interface/templates/label/optional_floating.sql
@@application/shared_components/user_interface/templates/label/hidden.sql
@@application/shared_components/user_interface/templates/label/optional.sql
@@application/shared_components/user_interface/templates/label/optional_above.sql
@@application/shared_components/user_interface/templates/label/required.sql
@@application/shared_components/user_interface/templates/label/required_above.sql
@@application/shared_components/user_interface/templates/breadcrumb/breadcrumb.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/templates/calendar/calendar.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/theme_display_points.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/globalization/translations.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/user_interface/shortcuts/timezone.sql
@@application/shared_components/user_interface/shortcuts/delete_confirm_msg.sql
@@application/shared_components/security/authentications/application_express.sql
@@application/shared_components/plugins/region_type/com_oracle_apex_translated_message.sql
@@application/shared_components/plugins/region_type/com_oracle_apex_acl_status.sql
@@application/shared_components/plugins/region_type/com_oracle_apex_acl_warning.sql
@@application/shared_components/plugins/region_type/com_oracle_auth_administration.sql
@@application/shared_components/plugins/region_type/com_oracle_apex_timelinestatuslist.sql
@@application/shared_components/plugins/region_type/com_oracle_apex_tag_cloud.sql
@@application/user_interfaces.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00004.sql
@@application/pages/page_00005.sql
@@application/pages/page_00007.sql
@@application/pages/page_00008.sql
@@application/pages/page_00009.sql
@@application/pages/page_00010.sql
@@application/pages/page_00011.sql
@@application/pages/page_00012.sql
@@application/pages/page_00013.sql
@@application/pages/page_00014.sql
@@application/pages/page_00015.sql
@@application/pages/page_00016.sql
@@application/pages/page_00017.sql
@@application/pages/page_00018.sql
@@application/pages/page_00019.sql
@@application/pages/page_00020.sql
@@application/pages/page_00021.sql
@@application/pages/page_00022.sql
@@application/pages/page_00023.sql
@@application/pages/page_00024.sql
@@application/pages/page_00025.sql
@@application/pages/page_00026.sql
@@application/pages/page_00027.sql
@@application/pages/page_00028.sql
@@application/pages/page_00029.sql
@@application/pages/page_00030.sql
@@application/pages/page_00031.sql
@@application/pages/page_00032.sql
@@application/pages/page_00033.sql
@@application/pages/page_00034.sql
@@application/pages/page_00035.sql
@@application/pages/page_00036.sql
@@application/pages/page_00037.sql
@@application/pages/page_00038.sql
@@application/pages/page_00040.sql
@@application/pages/page_00041.sql
@@application/pages/page_00042.sql
@@application/pages/page_00043.sql
@@application/pages/page_00044.sql
@@application/pages/page_00053.sql
@@application/pages/page_00054.sql
@@application/pages/page_00092.sql
@@application/pages/page_00100.sql
@@application/pages/page_00101.sql
@@application/pages/page_00175.sql
@@application/pages/page_01000.sql
@@application/pages/page_01001.sql
@@application/deployment/definition.sql
@@application/deployment/install/install_set_plscope_settings.sql
@@application/deployment/install/upgrade_framework_package.sql
@@application/deployment/install/install_error_log.sql
@@application/deployment/install/upgrade_framework_body.sql
@@application/deployment/install/install_framework_spec.sql
@@application/deployment/install/upgrade_username_format_preference.sql
@@application/deployment/install/upgrade_remove_help_table.sql
@@application/deployment/install/upgrade_adding_multi_calendar_mode.sql
@@application/deployment/install/upgrade_sample_data_package.sql
@@application/deployment/install/upgrade_more_event_colors.sql
@@application/deployment/install/upgrade_set_first_run_preference.sql
@@application/deployment/install/upgrade_update_event_types.sql
@@application/deployment/install/upgrade_eba_ca_api_spec.sql
@@application/deployment/install/upgrade_eba_ca_api_body.sql
@@application/deployment/install/install_eba_ca_api_spec.sql
@@application/deployment/install/upgrade_remove_eba_ca_admins_not_used.sql
@@application/deployment/install/upgrade_eba_ca_package.sql
@@application/deployment/install/upgrade_timestamp_fix_bugid_31352674.sql
@@application/deployment/install/install_color_prefs.sql
@@application/deployment/install/install_event_types.sql
@@application/deployment/install/install_events_seq.sql
@@application/deployment/install/install_history.sql
@@application/deployment/install/install_series.sql
@@application/deployment/install/install_tags.sql
@@application/deployment/install/install_calendars.sql
@@application/deployment/install/install_events.sql
@@application/deployment/install/install_event_notes.sql
@@application/deployment/install/install_files.sql
@@application/deployment/install/install_event_groups.sql
@@application/deployment/install/install_group_members.sql
@@application/deployment/install/install_timeframes.sql
@@application/deployment/install/install_admins_to_be_replaced_with_new_std_code.sql
@@application/deployment/install/install_notifications.sql
@@application/deployment/install/install_tz_prefs.sql
@@application/deployment/install/install_eba_ca_api_body.sql
@@application/deployment/install/install_eba_ca_specs.sql
@@application/deployment/install/install_acl_tables.sql
@@application/deployment/install/install_framework_body.sql
@@application/deployment/install/install_eba_ca_body.sql
@@application/deployment/install/install_events_triggers.sql
@@application/deployment/install/events_history_trigger.sql
@@application/deployment/install/install_install_the_acl_seed_data.sql
@@application/deployment/install/install_sample_data.sql
@@application/deployment/install/install_set_first_run_preference.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
