prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/plugin_settings.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/page/login.sql
@@application/shared_components/user_interface/templates/page/minimal_page.sql
@@application/shared_components/user_interface/templates/page/no_tabs_left_sidebar.sql
@@application/shared_components/user_interface/templates/page/no_tabs_left_and_right_sidebar.sql
@@application/shared_components/user_interface/templates/page/no_tabs_no_sidebar.sql
@@application/shared_components/user_interface/templates/page/no_tabs_right_sidebar.sql
@@application/shared_components/user_interface/templates/page/one_level_tabs_content_frame.sql
@@application/shared_components/user_interface/templates/page/one_level_tabs_left_sidebar.sql
@@application/shared_components/user_interface/templates/page/one_level_tabs_left_and_right_sidebar.sql
@@application/shared_components/user_interface/templates/page/one_level_tabs_no_sidebar.sql
@@application/shared_components/user_interface/templates/page/one_level_tabs_right_sidebar.sql
@@application/shared_components/user_interface/templates/page/one_level_tabs_search_filter_bar.sql
@@application/shared_components/user_interface/templates/page/one_level_tabs_wizard_page.sql
@@application/shared_components/user_interface/templates/page/popup.sql
@@application/shared_components/user_interface/templates/page/printer_friendly.sql
@@application/shared_components/user_interface/templates/page/two_level_tabs_left_sidebar.sql
@@application/shared_components/user_interface/templates/page/two_level_tabs_left_and_right_sidebar.sql
@@application/shared_components/user_interface/templates/page/two_level_tabs_no_sidebar.sql
@@application/shared_components/user_interface/templates/page/two_level_tabs_right_sidebar.sql
@@application/shared_components/user_interface/templates/button/button.sql
@@application/shared_components/user_interface/templates/button/interactive_report_button.sql
@@application/shared_components/user_interface/templates/button/interactive_report_button_next.sql
@@application/shared_components/user_interface/templates/button/large_button.sql
@@application/shared_components/user_interface/templates/button/large_button_next.sql
@@application/shared_components/user_interface/templates/button/large_button_previous.sql
@@application/shared_components/user_interface/templates/button/small_button.sql
@@application/shared_components/user_interface/templates/button/add_button.sql
@@application/shared_components/user_interface/templates/button/go_to_button.sql
@@application/shared_components/user_interface/templates/button/text_button.sql
@@application/shared_components/user_interface/templates/region/accessible_region_with_heading.sql
@@application/shared_components/user_interface/templates/region/alert_region.sql
@@application/shared_components/user_interface/templates/region/borderless_region.sql
@@application/shared_components/user_interface/templates/region/borderless_region_no_heading.sql
@@application/shared_components/user_interface/templates/region/bracketed_region.sql
@@application/shared_components/user_interface/templates/region/breadcrumb_region.sql
@@application/shared_components/user_interface/templates/region/button_region_with_title.sql
@@application/shared_components/user_interface/templates/region/button_region_without_title.sql
@@application/shared_components/user_interface/templates/region/chart_list.sql
@@application/shared_components/user_interface/templates/region/chart_region.sql
@@application/shared_components/user_interface/templates/region/content_frame_body_container.sql
@@application/shared_components/user_interface/templates/region/div_region_with_id.sql
@@application/shared_components/user_interface/templates/region/form_region.sql
@@application/shared_components/user_interface/templates/region/hide_and_show_region.sql
@@application/shared_components/user_interface/templates/region/hide_and_show_region_hidden_first_borderless.sql
@@application/shared_components/user_interface/templates/region/hide_and_show_region_borderless.sql
@@application/shared_components/user_interface/templates/region/interactive_report_region.sql
@@application/shared_components/user_interface/templates/region/login_region.sql
@@application/shared_components/user_interface/templates/region/modal_region.sql
@@application/shared_components/user_interface/templates/region/navigation_region.sql
@@application/shared_components/user_interface/templates/region/navigation_region_heading_inside.sql
@@application/shared_components/user_interface/templates/region/region_without_buttons_and_titles.sql
@@application/shared_components/user_interface/templates/region/region_without_title.sql
@@application/shared_components/user_interface/templates/region/report_filter_single_row.sql
@@application/shared_components/user_interface/templates/region/report_list.sql
@@application/shared_components/user_interface/templates/region/reports_region.sql
@@application/shared_components/user_interface/templates/region/reports_region_100_width.sql
@@application/shared_components/user_interface/templates/region/reports_region_heading_inside.sql
@@application/shared_components/user_interface/templates/region/scrollable_content_region.sql
@@application/shared_components/user_interface/templates/region/search_filter_region.sql
@@application/shared_components/user_interface/templates/region/sidebar_region.sql
@@application/shared_components/user_interface/templates/region/sidebar_region_heading_inside.sql
@@application/shared_components/user_interface/templates/region/wizard_buttons.sql
@@application/shared_components/user_interface/templates/region/wizard_region.sql
@@application/shared_components/user_interface/templates/region/wizard_region_with_icon.sql
@@application/shared_components/user_interface/templates/region/jquery_modal_region_template.sql
@@application/shared_components/user_interface/templates/list/button_list.sql
@@application/shared_components/user_interface/templates/list/dhtml_tree.sql
@@application/shared_components/user_interface/templates/list/featured_list_with_subtext.sql
@@application/shared_components/user_interface/templates/list/hierarchical_expanding.sql
@@application/shared_components/user_interface/templates/list/horizontal_images_with_label_list.sql
@@application/shared_components/user_interface/templates/list/horizontal_links_list.sql
@@application/shared_components/user_interface/templates/list/horizontal_wizard_progress_list.sql
@@application/shared_components/user_interface/templates/list/page_level_tabs_list.sql
@@application/shared_components/user_interface/templates/list/pull_down_menu.sql
@@application/shared_components/user_interface/templates/list/pull_down_menu_with_image.sql
@@application/shared_components/user_interface/templates/list/search_filter_tabs.sql
@@application/shared_components/user_interface/templates/list/tabbed_navigation_list.sql
@@application/shared_components/user_interface/templates/list/vertical_images_list.sql
@@application/shared_components/user_interface/templates/list/vertical_list_with_subtext_and_icon.sql
@@application/shared_components/user_interface/templates/list/vertical_ordered_list.sql
@@application/shared_components/user_interface/templates/list/vertical_sidebar_list.sql
@@application/shared_components/user_interface/templates/list/vertical_unordered_list_with_bullets.sql
@@application/shared_components/user_interface/templates/list/vertical_unordered_list_without_bullets.sql
@@application/shared_components/user_interface/templates/list/wizard_progress_list_vertical.sql
@@application/shared_components/user_interface/templates/report/borderless_report.sql
@@application/shared_components/user_interface/templates/report/comment_bubbles.sql
@@application/shared_components/user_interface/templates/report/fixed_headers.sql
@@application/shared_components/user_interface/templates/report/horizontal_border.sql
@@application/shared_components/user_interface/templates/report/one_column_unordered_list.sql
@@application/shared_components/user_interface/templates/report/search_results_report_select_link_text_link_target_detail1_detail2_last_modified.sql
@@application/shared_components/user_interface/templates/report/standard.sql
@@application/shared_components/user_interface/templates/report/standard_alternative.sql
@@application/shared_components/user_interface/templates/report/two_column_portlet.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_left_aligned.sql
@@application/shared_components/user_interface/templates/report/standard_logs_borderless.sql
@@application/shared_components/user_interface/templates/label/hidden_label_read_by_screen_reader.sql
@@application/shared_components/user_interface/templates/label/no_label.sql
@@application/shared_components/user_interface/templates/label/optional.sql
@@application/shared_components/user_interface/templates/label/optional_with_help.sql
@@application/shared_components/user_interface/templates/label/required.sql
@@application/shared_components/user_interface/templates/label/required_with_help.sql
@@application/shared_components/user_interface/templates/breadcrumb/breadcrumb_menu.sql
@@application/shared_components/user_interface/templates/breadcrumb/hierarchical_menu.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/templates/calendar/calendar.sql
@@application/shared_components/user_interface/templates/calendar/calendar_alternative.sql
@@application/shared_components/user_interface/templates/calendar/small_calendar.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/theme_display_points.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/globalization/translations.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/security/authentications/application_express_authentication.sql
@@application/user_interfaces.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00005.sql
@@application/pages/page_00101.sql
@@application/deployment/definition.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
