prompt --application/pages/page_00028
begin
--   Manifest
--     PAGE: 00028
--   Manifest End
wwv_flow_api.component_begin (
 p_version_yyyy_mm_dd=>'2021.04.15'
,p_release=>'21.1.7'
,p_default_workspace_id=>9008156634332785
,p_default_application_id=>100
,p_default_id_offset=>0
,p_default_owner=>'MISO'
);
wwv_flow_api.create_page(
 p_id=>28
,p_user_interface_id=>wwv_flow_api.id(46185900950878783)
,p_name=>'svc1'
,p_alias=>'SVC1'
,p_step_title=>'svc1'
,p_autocomplete_on_off=>'OFF'
,p_page_template_options=>'#DEFAULT#'
,p_last_updated_by=>'MISO'
,p_last_upd_yyyymmddhh24miss=>'20211031020522'
);
wwv_flow_api.create_report_region(
 p_id=>wwv_flow_api.id(46726991696443931)
,p_name=>'Report 1'
,p_template=>wwv_flow_api.id(46096392003878711)
,p_display_sequence=>10
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_component_template_options=>'#DEFAULT#:t-Report--altRowsDefault:t-Report--rowHighlight'
,p_display_point=>'BODY'
,p_source_type=>'NATIVE_SQL_REPORT'
,p_location=>'WEB_SOURCE'
,p_web_src_module_id=>wwv_flow_api.id(46724304797424543)
,p_query_type=>'FUNC_BODY_RETURNING_SQL'
,p_function_body_language=>'PLSQL'
,p_ajax_enabled=>'Y'
,p_lazy_loading=>false
,p_query_row_template=>wwv_flow_api.id(46120000409878727)
,p_query_num_rows=>15
,p_query_options=>'DERIVED_REPORT_COLUMNS'
,p_query_no_data_found=>'no data found'
,p_query_num_rows_type=>'NEXT_PREVIOUS_LINKS'
,p_query_row_count_max=>500
,p_csv_output=>'Y'
,p_csv_output_link_text=>'Download'
,p_prn_output=>'N'
,p_prn_format=>'PDF'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(46727373213443947)
,p_query_column_id=>1
,p_column_alias=>'REL'
,p_column_display_sequence=>10
,p_column_heading=>'Rel'
,p_default_sort_column_sequence=>1
,p_disable_sort_column=>'N'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(46727793286443948)
,p_query_column_id=>2
,p_column_alias=>'TYPE'
,p_column_display_sequence=>20
,p_column_heading=>'Type'
,p_disable_sort_column=>'N'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(46728149084443948)
,p_query_column_id=>3
,p_column_alias=>'HREF'
,p_column_display_sequence=>30
,p_column_heading=>'Href'
,p_disable_sort_column=>'N'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(46728514525443948)
,p_query_column_id=>4
,p_column_alias=>'TYPE2'
,p_column_display_sequence=>40
,p_column_heading=>'Type2'
,p_disable_sort_column=>'N'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(46728973088443948)
,p_query_column_id=>5
,p_column_alias=>'STYLE'
,p_column_display_sequence=>50
,p_column_heading=>'Style'
,p_disable_sort_column=>'N'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(46729317058443949)
,p_query_column_id=>6
,p_column_alias=>'TITLE'
,p_column_display_sequence=>60
,p_column_heading=>'Title'
,p_disable_sort_column=>'N'
);
wwv_flow_api.component_end;
end;
/
