prompt --application/pages/page_00010
begin
--   Manifest
--     PAGE: 00010
--   Manifest End
wwv_flow_api.component_begin (
 p_version_yyyy_mm_dd=>'2021.04.15'
,p_release=>'21.1.7'
,p_default_workspace_id=>9008156634332785
,p_default_application_id=>121
,p_default_id_offset=>0
,p_default_owner=>'MISO'
);
wwv_flow_api.create_page(
 p_id=>10
,p_user_interface_id=>wwv_flow_api.id(95153343667962421)
,p_name=>'DATADOG_MONITOR'
,p_alias=>'DATADOG-MONITOR'
,p_step_title=>'DATADOG_MONITOR'
,p_autocomplete_on_off=>'OFF'
,p_page_template_options=>'#DEFAULT#'
,p_last_updated_by=>'CR_COFFEE'
,p_last_upd_yyyymmddhh24miss=>'20220204063317'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(96168172305126386)
,p_plug_name=>'DATADOG_MONITOR'
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_api.id(95050013540962342)
,p_plug_display_sequence=>10
,p_plug_display_point=>'BODY'
,p_query_type=>'TABLE'
,p_query_table=>'DATADOG__MONITOR__JSON'
,p_include_rowid_column=>false
,p_plug_source_type=>'NATIVE_IR'
,p_prn_page_header=>'DATADOG_MONITOR'
);
wwv_flow_api.create_worksheet(
 p_id=>wwv_flow_api.id(96168277628126386)
,p_name=>'DATADOG_MONITOR'
,p_max_row_count_message=>'The maximum row count for this report is #MAX_ROW_COUNT# rows.  Please apply a filter to reduce the number of records in your query.'
,p_no_data_found_message=>'No data found.'
,p_pagination_type=>'ROWS_X_TO_Y'
,p_pagination_display_pos=>'BOTTOM_RIGHT'
,p_report_list_mode=>'TABS'
,p_lazy_loading=>false
,p_show_detail_link=>'N'
,p_download_formats=>'CSV:HTML:EMAIL:XLSX:PDF:RTF'
,p_owner=>'MISO'
,p_internal_uid=>96168277628126386
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(96168627415126395)
,p_db_column_name=>'ID_1'
,p_display_order=>1
,p_column_identifier=>'A'
,p_column_label=>'Id 1'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(96169033546126397)
,p_db_column_name=>'ID'
,p_display_order=>2
,p_column_identifier=>'B'
,p_column_label=>'Id'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(96169496263126397)
,p_db_column_name=>'NAME'
,p_display_order=>3
,p_column_identifier=>'C'
,p_column_label=>'Name'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(96169862351126398)
,p_db_column_name=>'TYPE'
,p_display_order=>4
,p_column_identifier=>'D'
,p_column_label=>'Type'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(96170209197126398)
,p_db_column_name=>'MULTI'
,p_display_order=>5
,p_column_identifier=>'E'
,p_column_label=>'Multi'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(96170642298126398)
,p_db_column_name=>'QUERY'
,p_display_order=>6
,p_column_identifier=>'F'
,p_column_label=>'Query'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(96171016330126399)
,p_db_column_name=>'ORG_ID'
,p_display_order=>7
,p_column_identifier=>'G'
,p_column_label=>'Org Id'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(96171478962126399)
,p_db_column_name=>'CREATED'
,p_display_order=>8
,p_column_identifier=>'H'
,p_column_label=>'Created'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(96171808104126399)
,p_db_column_name=>'ID2'
,p_display_order=>9
,p_column_identifier=>'I'
,p_column_label=>'Id2'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(96172221285126399)
,p_db_column_name=>'NAME2'
,p_display_order=>10
,p_column_identifier=>'J'
,p_column_label=>'Name2'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(96172663096126400)
,p_db_column_name=>'EMAIL'
,p_display_order=>11
,p_column_identifier=>'K'
,p_column_label=>'Email'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(96173014397126400)
,p_db_column_name=>'HANDLE'
,p_display_order=>12
,p_column_identifier=>'L'
,p_column_label=>'Handle'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(96173478327126400)
,p_db_column_name=>'DELETED'
,p_display_order=>13
,p_column_identifier=>'M'
,p_column_label=>'Deleted'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(96173810450126400)
,p_db_column_name=>'MESSAGE'
,p_display_order=>14
,p_column_identifier=>'N'
,p_column_label=>'Message'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(96174246321126400)
,p_db_column_name=>'LOCKED'
,p_display_order=>15
,p_column_identifier=>'O'
,p_column_label=>'Locked'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(96174622192126401)
,p_db_column_name=>'TIMEOUT_H'
,p_display_order=>16
,p_column_identifier=>'P'
,p_column_label=>'Timeout H'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(96175055571126401)
,p_db_column_name=>'CRITICAL'
,p_display_order=>17
,p_column_identifier=>'Q'
,p_column_label=>'Critical'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(96175436755126401)
,p_db_column_name=>'INCLUDE_TAGS'
,p_display_order=>18
,p_column_identifier=>'R'
,p_column_label=>'Include Tags'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(96175805794126401)
,p_db_column_name=>'NOTIFY_AUDIT'
,p_display_order=>19
,p_column_identifier=>'S'
,p_column_label=>'Notify Audit'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(96176230835126402)
,p_db_column_name=>'NEW_HOST_DELAY'
,p_display_order=>20
,p_column_identifier=>'T'
,p_column_label=>'New Host Delay'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(96176693942126402)
,p_db_column_name=>'NOTIFY_NO_DATA'
,p_display_order=>21
,p_column_identifier=>'U'
,p_column_label=>'Notify No Data'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(96177078504126402)
,p_db_column_name=>'NO_DATA_TIMEFRAME'
,p_display_order=>22
,p_column_identifier=>'V'
,p_column_label=>'No Data Timeframe'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(96177414134126402)
,p_db_column_name=>'RENOTIFY_INTERVAL'
,p_display_order=>23
,p_column_identifier=>'W'
,p_column_label=>'Renotify Interval'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(96177855338126403)
,p_db_column_name=>'RENOTIFY_STATUSES'
,p_display_order=>24
,p_column_identifier=>'X'
,p_column_label=>'Renotify Statuses'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(96178273832126403)
,p_db_column_name=>'ESCALATION_MESSAGE'
,p_display_order=>25
,p_column_identifier=>'Y'
,p_column_label=>'Escalation Message'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(96178660241126403)
,p_db_column_name=>'REQUIRE_FULL_WINDOW'
,p_display_order=>26
,p_column_identifier=>'Z'
,p_column_label=>'Require Full Window'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(96179025441126404)
,p_db_column_name=>'RENOTIFY_OCCURRENCES'
,p_display_order=>27
,p_column_identifier=>'AA'
,p_column_label=>'Renotify Occurrences'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(96179431038126404)
,p_db_column_name=>'MODIFIED'
,p_display_order=>28
,p_column_identifier=>'AB'
,p_column_label=>'Modified'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(96179810859126404)
,p_db_column_name=>'PRIORITY'
,p_display_order=>29
,p_column_identifier=>'AC'
,p_column_label=>'Priority'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(96180206946126404)
,p_db_column_name=>'CREATED_AT'
,p_display_order=>30
,p_column_identifier=>'AD'
,p_column_label=>'Created At'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(96180616595126405)
,p_db_column_name=>'OVERALL_STATE'
,p_display_order=>31
,p_column_identifier=>'AE'
,p_column_label=>'Overall State'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(96181077722126405)
,p_db_column_name=>'RESTRICTED_ROLES'
,p_display_order=>32
,p_column_identifier=>'AF'
,p_column_label=>'Restricted Roles'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(96181413954126405)
,p_db_column_name=>'OVERALL_STATE_MODIFIED'
,p_display_order=>33
,p_column_identifier=>'AG'
,p_column_label=>'Overall State Modified'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_rpt(
 p_id=>wwv_flow_api.id(96182006432129582)
,p_application_user=>'APXWS_DEFAULT'
,p_report_seq=>10
,p_report_alias=>'961821'
,p_status=>'PUBLIC'
,p_is_default=>'Y'
,p_report_columns=>'ID_1:ID:NAME:TYPE:MULTI:QUERY:ORG_ID:CREATED:ID2:NAME2:EMAIL:HANDLE:DELETED:MESSAGE:LOCKED:TIMEOUT_H:CRITICAL:INCLUDE_TAGS:NOTIFY_AUDIT:NEW_HOST_DELAY:NOTIFY_NO_DATA:NO_DATA_TIMEFRAME:RENOTIFY_INTERVAL:RENOTIFY_STATUSES:ESCALATION_MESSAGE:REQUIRE_FUL'
||'L_WINDOW:RENOTIFY_OCCURRENCES:MODIFIED:PRIORITY:CREATED_AT:OVERALL_STATE:RESTRICTED_ROLES:OVERALL_STATE_MODIFIED'
);
wwv_flow_api.component_end;
end;
/
