prompt --application/pages/page_00008
begin
--   Manifest
--     PAGE: 00008
--   Manifest End
wwv_flow_api.component_begin (
 p_version_yyyy_mm_dd=>'2021.04.15'
,p_release=>'21.1.7'
,p_default_workspace_id=>9008156634332785
,p_default_application_id=>133
,p_default_id_offset=>0
,p_default_owner=>'MISO'
);
wwv_flow_api.create_page(
 p_id=>8
,p_user_interface_id=>wwv_flow_api.id(104891014803699938)
,p_name=>'GCP CMA COOKTIMES'
,p_alias=>'SAM-PROVIDED-BIGQUERY-DATAFILES'
,p_step_title=>'SAM PROVIDED BIGQUERY DATAFILES'
,p_autocomplete_on_off=>'OFF'
,p_page_template_options=>'#DEFAULT#'
,p_last_updated_by=>'MISO'
,p_last_upd_yyyymmddhh24miss=>'20220308001342'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(105534529139276138)
,p_plug_name=>'CMA_DATA'
,p_region_template_options=>'#DEFAULT#:is-expanded:t-Region--scrollBody'
,p_plug_template=>wwv_flow_api.id(104781806506699849)
,p_plug_display_sequence=>10
,p_include_in_reg_disp_sel_yn=>'Y'
,p_plug_display_point=>'BODY'
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_attribute_01=>'N'
,p_attribute_02=>'HTML'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(105533920009276132)
,p_plug_name=>'BIGQUERY_COOK_TIMES'
,p_parent_plug_id=>wwv_flow_api.id(105534529139276138)
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_api.id(104801457324699859)
,p_plug_display_sequence=>20
,p_plug_display_point=>'BODY'
,p_query_type=>'TABLE'
,p_query_table=>'GCP_BIGQUERY_COOK_TIMES'
,p_include_rowid_column=>false
,p_plug_source_type=>'NATIVE_IR'
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_prn_content_disposition=>'ATTACHMENT'
,p_prn_document_header=>'APEX'
,p_prn_units=>'INCHES'
,p_prn_paper_size=>'LETTER'
,p_prn_width=>11
,p_prn_height=>8.5
,p_prn_orientation=>'HORIZONTAL'
,p_prn_page_header=>'BIGQUERY_COOK_TIMES'
,p_prn_page_header_font_color=>'#000000'
,p_prn_page_header_font_family=>'Helvetica'
,p_prn_page_header_font_weight=>'normal'
,p_prn_page_header_font_size=>'12'
,p_prn_page_footer_font_color=>'#000000'
,p_prn_page_footer_font_family=>'Helvetica'
,p_prn_page_footer_font_weight=>'normal'
,p_prn_page_footer_font_size=>'12'
,p_prn_header_bg_color=>'#EEEEEE'
,p_prn_header_font_color=>'#000000'
,p_prn_header_font_family=>'Helvetica'
,p_prn_header_font_weight=>'bold'
,p_prn_header_font_size=>'10'
,p_prn_body_bg_color=>'#FFFFFF'
,p_prn_body_font_color=>'#000000'
,p_prn_body_font_family=>'Helvetica'
,p_prn_body_font_weight=>'normal'
,p_prn_body_font_size=>'10'
,p_prn_border_width=>.5
,p_prn_page_header_alignment=>'CENTER'
,p_prn_page_footer_alignment=>'CENTER'
,p_prn_border_color=>'#666666'
);
wwv_flow_api.create_worksheet(
 p_id=>wwv_flow_api.id(105534076289276133)
,p_max_row_count=>'1000000'
,p_allow_save_rpt_public=>'Y'
,p_pagination_type=>'ROWS_X_TO_Y_OF_Z'
,p_pagination_display_pos=>'TOP_AND_BOTTOM_LEFT'
,p_show_display_row_count=>'Y'
,p_report_list_mode=>'TABS'
,p_lazy_loading=>false
,p_show_detail_link=>'N'
,p_show_notify=>'Y'
,p_download_formats=>'CSV:HTML:XLSX:PDF:RTF:EMAIL'
,p_download_filename=>'BQ_COOK_TIMES'
,p_csv_output_separator=>','
,p_csv_output_enclosed_by=>'"'
,p_supplemental_text=>'https://gd49ef7d5e3cd2d-db202110212330.adb.us-phoenix-1.oraclecloudapps.com/ords/r/miso/my-metadata-oracle-to-bigquery/ miso Epfy44yqE_WEB'
,p_owner=>'MISO'
,p_internal_uid=>105534076289276133
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(105534177749276134)
,p_db_column_name=>'ID'
,p_display_order=>10
,p_column_identifier=>'A'
,p_column_label=>'Id'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(105534226754276135)
,p_db_column_name=>'FOOD_TYPE'
,p_display_order=>20
,p_column_identifier=>'B'
,p_column_label=>'Food Type'
,p_column_type=>'STRING'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(105534388836276136)
,p_db_column_name=>'MAX_COOKTIME_SECS'
,p_display_order=>30
,p_column_identifier=>'C'
,p_column_label=>'Max Cooktime Secs'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(105534400854276137)
,p_db_column_name=>'STORE'
,p_display_order=>40
,p_column_identifier=>'D'
,p_column_label=>'Store'
,p_column_type=>'STRING'
);
wwv_flow_api.create_worksheet_rpt(
 p_id=>wwv_flow_api.id(106174150148223453)
,p_application_user=>'APXWS_DEFAULT'
,p_report_seq=>10
,p_report_alias=>'1061742'
,p_status=>'PUBLIC'
,p_is_default=>'Y'
,p_report_columns=>'ID:FOOD_TYPE:MAX_COOKTIME_SECS:STORE'
,p_sort_column_1=>'FOOD_TYPE'
,p_sort_direction_1=>'DESC'
,p_sort_column_2=>'STORE'
,p_sort_direction_2=>'DESC'
);
wwv_flow_api.create_worksheet_condition(
 p_id=>wwv_flow_api.id(106049792092987438)
,p_report_id=>wwv_flow_api.id(106174150148223453)
,p_name=>'CB'
,p_condition_type=>'HIGHLIGHT'
,p_allow_delete=>'Y'
,p_column_name=>'STORE'
,p_operator=>'='
,p_expr=>'Caliburger'
,p_condition_sql=>' (case when ("STORE" = #APXWS_EXPR#) then #APXWS_HL_ID# end) '
,p_condition_display=>'#APXWS_COL_NAME# = ''Caliburger''  '
,p_enabled=>'Y'
,p_highlight_sequence=>10
,p_column_bg_color=>'#948efd'
);
wwv_flow_api.create_worksheet_condition(
 p_id=>wwv_flow_api.id(106050134419987439)
,p_report_id=>wwv_flow_api.id(106174150148223453)
,p_name=>'WC'
,p_condition_type=>'HIGHLIGHT'
,p_allow_delete=>'Y'
,p_column_name=>'STORE'
,p_operator=>'='
,p_expr=>'White Castle'
,p_condition_sql=>' (case when ("STORE" = #APXWS_EXPR#) then #APXWS_HL_ID# end) '
,p_condition_display=>'#APXWS_COL_NAME# = ''White Castle''  '
,p_enabled=>'Y'
,p_highlight_sequence=>10
,p_column_bg_color=>'#f6b9b9'
);
wwv_flow_api.create_worksheet_condition(
 p_id=>wwv_flow_api.id(106050532712987439)
,p_report_id=>wwv_flow_api.id(106174150148223453)
,p_name=>'KFC'
,p_condition_type=>'HIGHLIGHT'
,p_allow_delete=>'Y'
,p_column_name=>'STORE'
,p_operator=>'='
,p_expr=>'KFC'
,p_condition_sql=>' (case when ("STORE" = #APXWS_EXPR#) then #APXWS_HL_ID# end) '
,p_condition_display=>'#APXWS_COL_NAME# = ''KFC''  '
,p_enabled=>'Y'
,p_highlight_sequence=>10
,p_column_bg_color=>'#0c8c31'
);
wwv_flow_api.component_end;
end;
/
