prompt --application/pages/page_00060
begin
--   Manifest
--     PAGE: 00060
--   Manifest End
wwv_flow_api.component_begin (
 p_version_yyyy_mm_dd=>'2021.04.15'
,p_release=>'21.1.7'
,p_default_workspace_id=>9008156634332785
,p_default_application_id=>104
,p_default_id_offset=>0
,p_default_owner=>'MISO'
);
wwv_flow_api.create_page(
 p_id=>60
,p_user_interface_id=>wwv_flow_api.id(41820330279533220)
,p_name=>'meta'
,p_alias=>'META'
,p_step_title=>'meta'
,p_autocomplete_on_off=>'OFF'
,p_page_template_options=>'#DEFAULT#'
,p_last_updated_by=>'MISO'
,p_last_upd_yyyymmddhh24miss=>'20211023200458'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(21433000843197720)
,p_plug_name=>'New'
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_plug_template=>wwv_flow_api.id(41730750648533116)
,p_plug_display_sequence=>10
,p_include_in_reg_disp_sel_yn=>'Y'
,p_plug_display_point=>'BODY'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<PRE>',
'--Transition Team1',
'Author  /insert 2  /history /audit',
'   author_id /pk',
'   author_name       ',
'   author_email              /unique  ',
'   author_contact_other     ',
'   author_source_type        /check miso, cke, external, partner, internal , hybrid ',
'',
'document_status /insert 5  /history /audit',
'   document_status_id /pk  ',
'   document_status_name /check completed,wip,rejected, review,other, poc, pending_review',
'   document_desc',
'',
'document_Type /insert 5  /history /audit',
'   document_type_id  /pk  ',
'   document_type_name /check  sql, text,pdf,word,excel,ppt, restapi, json,other',
'   docuemnt_desc',
'',
'document_key_words',
'   key_words_id ',
'   key_words',
'   desc',
'',
'document /insert 5  /history /audit',
'   document_id    /pk',
'   document_name        ',
'   document_type_ID    /references document_Type  ',
'   document_status_ID  /references document_status ',
'   docuemnt_desc',
'   file_uploaded   file',
'',
'document_word_asc',
'   document_word_asc_id   /pk    ',
'   document_id           /references document ',
'   document_key_words_id /references document_key_words',
'   ',
'',
'author_document_asc  /insert 5  /history /audit',
'   author_document_asc_id /pk',
'   contrib_order  number  /check 1,2,3,4,5',
'   author_id    /references author',
'   document_id  /references document ',
'',
'system_name /insert 5  /history /audit',
'   system_name_id /pk',
'   system_name',
'   system_type   /check  flippy, sippy, cke, api, etc',
'   system_desc',
'',
'business_process /insert 5  /history /audit',
'   business_process_id /pk',
'   process_name',
'   process_desc',
'   other_details',
'   next_business_process_id /references wb_business_process ',
'',
'system_business_process_asc /insert 5  /history /audit',
'   sbpa_id /pk',
'   system_cnt          number ',
'   system_name_id      /references system_name',
'   business_process_id /references business_process    ',
'',
'event_type  /insert 5  /history /audit',
'   event_type_id /pk',
'   event_type_code',
'   event_type_desc',
'',
'event  /insert 5  /history /audit',
'   event_id /pk',
'   next_event_id /references wb_event      ',
'   event_type    /references wb_event_type ',
'   event_name',
'   event_Desc',
'   other_details',
'',
'bus_process_event_possible  /insert 5  /history /audit',
'  bus_process_event_possible_id  /pk',
'  retired_state   /check y,n,?',
'  bpep_order      number',
'  event_id        /references event            ',
'  bus_process_id  /references wb_business_process ',
'',
'transaction_type  /insert 5  /history /audit',
'  transaction_type_id /pk',
'  tranaction_type_code',
'  tranaction_type_desc',
'',
'transaction  /insert 5  /history /audit',
'  transaction_id /pk',
'  tranaction_type_id /references wb_transaction_type ',
'  tranaction_type_desc',
'',
'act_bus_process_event  /insert 5  /history /audit',
'      act_bus_process_event_id /pk',
'      bus_process_event_possible_id   /references wb_bus_process_event_possible ',
'      transaction_id                  /references transaction              ',
'',
'resources  /insert 5  /history /audit',
'   id',
'   name             -- Kris',
'   role             -- cto',
'   company          -- misorobotics',
'   email            ',
'   phone ',
'   relation_type   /check report_to, pier, manage, vendor',
'   relation_hier   /references wb_resources ',
'   request_type    /check requests, is_requested, is_advised, no_action',
'',
'interface_file  /insert 5  /history /audit',
'   id                    ',
'   name                  vc4000  /unique',
'   pdf_file_content      file',
'   version_spec          vc4000',
'   details_from          /references wb_resources',
'   review_start_dt    date',
'   review_end_dt      date',
'   doc_status         /check poc,wip,current, retired  ',
'   ',
'',
'interface_source /insert 5  /history /audit',
'   id                    ',
'   name                  vc4000  /unique',
'   pdf_file_content      file',
'   version_spec          vc4000',
'   details_from          /references wb_resources',
'',
'interface_contrib /insert 5  /history /audit',
'   in',
'   role_in_lifecycle   /check provider, author, team_member_approval, reviewer',
'   contrib_start_dt    date',
'   contrib_end_dt      date',
'   contrib_status      vc4000  /check began_review, not_started, completed, wip, rewrite_state    ',
'',
'resource_contrib_file_asc /insert 5  /history /audit',
'   id ',
'   resources  /references wb_resources',
'   files      /references wb_interface_file',
'   contribute /references wb_interface_contrib',
'   start_dt   date ',
'   ',
'',
'interface_auth /insert 5  /history /audit',
'   access_token',
'   location_token',
'   url ',
'   sample_http_request',
'',
'',
'interface_actions /insert 5  /history /audit',
'   id ',
'   url_full_spec                  ',
'   method            /check get, put, post, delete',
'   detail_method',
'   processing_challenges ',
'   workflow_state    /check in_process, discussion, implementation',
'   source            /check internal_generated, external_live',
'',
'web_service_catalog /insert 5  /history /audit',
'   id',
'   url_endpoint   ',
'   authentication_type ',
'   methodof       /references wb_interface_actions ',
'',
'',
'auth_actions_asc /insert 5  /history /audit',
'   auth    /references wb_interface_auth',
'   actions /references wb_interface_actions',
'   start_dt   date ',
'',
'',
'catalog_actions_asc /insert 5  /history /audit',
'   web_catalog_ID    /references wb_web_service_catalog',
'   actions_ID        /references wb_interface_actions',
'   start_dt   date ',
'',
'</pre>'))
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_attribute_01=>'N'
,p_attribute_02=>'HTML'
);
wwv_flow_api.component_end;
end;
/
