prompt --application/deployment/install/install_7_day_history_view
begin
--   Manifest
--     INSTALL: INSTALL-7 Day History View
--   Manifest End
wwv_flow_api.component_begin (
 p_version_yyyy_mm_dd=>'2021.04.15'
,p_release=>'21.1.7'
,p_default_workspace_id=>9008156634332785
,p_default_application_id=>134
,p_default_id_offset=>172493832712964115
,p_default_owner=>'MISO'
);
wwv_flow_api.create_install_script(
 p_id=>wwv_flow_api.id(18353415113261180845)
,p_install_id=>wwv_flow_api.id(9012014618759672631)
,p_name=>'7 Day History View'
,p_sequence=>860
,p_script_type=>'INSTALL'
,p_script_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'create or replace view eba_proj_history_7day_v as',
'with build_options as (',
'    select build_option_name',
'    from apex_application_build_options',
'    where application_id = ( select v(''APP_ID'') from dual )',
'        and build_option_status = ''Include''',
')',
'    select ''Project Created'' comment_text,',
'           f.project as affected_item,',
'           '' '' attribute_1,',
'           '' '' attribute_2,',
'           lower(f.created_by) user_name,',
'           f.created comment_date,',
'           f.created,',
'           f.created_by as user_id,',
'           f.id as project_id',
'      from eba_proj_status f',
'     where f.created >= (trunc(sysdate) - 7)',
'union all',
'    select ''Project Removed'' comment_text,',
'           f.project as affected_item,',
'           '' '' attribute_1,',
'           '' '' attribute_2,',
'           lower(f.deleted_by) user_name,',
'           f.deleted_on comment_date,',
'           f.deleted_on,',
'           f.deleted_by as user_id,',
'           f.id as project_id',
'      from eba_proj_status$ f',
'     where f.is_deleted_yn = ''Y''',
'         and f.deleted_on >= (trunc(sysdate) - 7)',
'union all',
'    select ''Person Added'' comment_text,',
'           lower(u.username) as affected_item,',
'           '' '' attribute_1,',
'           '' '' attribute_2,',
'           lower(f.created_by) user_name,',
'           f.created comment_date,',
'           f.created,',
'           f.created_by as user_id,',
'           f.project_id',
'      from eba_proj_user_ref f,',
'           eba_proj_status_users u',
'     where f.user_id = u.id',
'       and f.created >= (trunc(sysdate) - 7)',
'union all',
'    select ''Attachment Added'' comment_text,',
'           f.filename affected_item,',
'           '' '' attribute_1,',
'           '' '' attribute_2,',
'           lower(f.created_by) user_name,',
'           f.created comment_date,',
'           f.created,',
'           f.created_by as user_id,',
'           f.project_id',
'      from eba_proj_status_files f',
'     where f.created >= (trunc(sysdate) - 7)',
'        and exists (select null',
'                    from build_options',
'                    where build_option_name = ''Project Attachments''',
'            )',
'union all',
'    select ''Country Added'' comment_text,',
'           c.country_name affected_item,',
'           '' '' attribute_1,',
'           '' '' attribute_2,',
'           lower(rf.created_by) user_name,',
'           rf.created comment_date,',
'           rf.created,',
'           rf.created_by as user_id,',
'           rf.project_id',
'      from eba_proj_status_country_ref rf,',
'        eba_proj_countries c',
'     where rf.created >= (trunc(sysdate) - 7)',
'        and c.id = rf.country_id',
'        and exists (select null',
'                    from build_options',
'                    where build_option_name = ''Project Countries''',
'            )',
'union all',
'    select ''Status Report Added'' comment_text,',
'           f.status_title as affected_item,',
'           '' '' attribute_1,',
'           '' '' attribute_2,',
'           lower(f.created_by) user_name,',
'           f.created comment_date,',
'           f.created,',
'           f.created_by as user_id,',
'           f.project_id',
'      from eba_proj_status_rpts f',
'     where f.created >= (trunc(sysdate) - 7)',
'        and exists (select null',
'                    from build_options',
'                    where build_option_name = ''Project Status Reports''',
'            )',
'union all',
'    select ''Link Added'' comment_text,',
'           f.link_target as affected_item,',
'           '' '' attribute_1,',
'           '' '' attribute_2,',
'           lower(f.created_by) user_name,',
'           f.created comment_date,',
'           f.created,',
'           f.created_by as user_id,',
'           f.project_id',
'      from eba_proj_status_links f',
'     where f.created >= (trunc(sysdate) - 7)',
'        and exists (select null',
'                    from build_options',
'                    where build_option_name = ''Project Links''',
'            )',
'union all',
'    select ''Milestone Added'' comment_text,',
'           f.milestone_name as affected_item,',
'           '' '' attribute_1,',
'           '' '' attribute_2,',
'           lower(f.created_by) user_name,',
'           f.created comment_date,',
'           f.created,',
'           f.created_by as user_id,',
'           f.project_id',
'      from eba_proj_status_ms f',
'     where f.created >= (trunc(sysdate) - 7)',
'        and exists (select null',
'                    from build_options',
'                    where build_option_name = ''Project Milestones''',
'            )',
'union all',
'    select ''Milestone Removed'' comment_text,',
'           f.milestone_name as affected_item,',
'           '' '' attribute_1,',
'           '' '' attribute_2,',
'           lower(f.deleted_by) user_name,',
'           f.deleted_on comment_date,',
'           f.deleted_on,',
'           f.deleted_by as user_id,',
'           f.project_id',
'      from eba_proj_status_ms$ f',
'     where f.is_deleted_yn = ''Y''',
'        and f.deleted_on >= (trunc(sysdate) - 7)',
'        and exists (select null',
'                    from build_options',
'                    where build_option_name = ''Project Milestones''',
'            )',
'union all',
'    select ''Action Item Added'' comment_text,',
'           f.action as affected_item,',
'           '' '' attribute_1,',
'           '' '' attribute_2,',
'           lower(f.created_by) user_name,',
'           f.created comment_date,',
'           f.created,',
'           f.created_by as user_id,',
'           f.project_id',
'      from eba_proj_status_ais f',
'     where f.created >= (trunc(sysdate) - 7)',
'        and exists (select null',
'                    from build_options',
'                    where build_option_name = ''Project Action Items''',
'            )',
'union all',
'    select ''Action Item Removed'' comment_text,',
'           f.action as affected_item,',
'           '' '' attribute_1,',
'           '' '' attribute_2,',
'           lower(f.deleted_by) user_name,',
'           f.deleted_on comment_date,',
'           f.deleted_on,',
'           f.deleted_by as user_id,',
'           f.project_id',
'      from eba_proj_status_ais$ f',
'     where f.is_deleted_yn = ''Y''',
'        and f.deleted_on >= (trunc(sysdate) - 7)',
'        and exists (select null',
'                    from build_options',
'                    where build_option_name = ''Project Action Items''',
'            )',
'union all',
'    select ''Verification Added'' comment_text,',
'           substr(f.verification_comment,1,100) as affected_item,',
'           '' '' attribute_1,',
'           '' '' attribute_2,',
'           lower(f.created_by) user_name,',
'           f.created comment_date,',
'           f.created,',
'           f.created_by as user_id,',
'           f.project_id',
'      from eba_proj_status_verifications f',
'     where f.created >= (trunc(sysdate) - 7)',
'union all',
'    select ''Update Added'' comment_text,',
'           case when dbms_lob.getlength(f.status_update) > 100 then',
'               dbms_lob.substr(f.status_update, 100, 1) || ''...''',
'           else',
'               dbms_lob.substr(f.status_update, 100, 1)',
'           end as affected_item,',
'           '' '' attribute_1,',
'           '' '' attribute_2,',
'           lower(f.created_by) user_name,',
'           f.created comment_date,',
'           f.created,',
'           f.created_by as user_id,',
'           f.project_id',
'      from eba_proj_status_updates f',
'     where f.created >= (trunc(sysdate) - 7)',
'        and exists (select null',
'                    from build_options',
'                    where build_option_name = ''Project Updates''',
'            )',
'union all',
'    select ''Issue Added'' comment_text,',
'           f.issue as affected_item,',
'           '' '' attribute_1,',
'           '' '' attribute_2,',
'           lower(f.created_by) user_name,',
'           f.created comment_date,',
'           f.created,',
'           f.created_by as user_id,',
'           f.project_id',
'      from eba_proj_status_issues f',
'     where f.created >= (trunc(sysdate) - 7)',
'        and exists (select null',
'                    from build_options',
'                    where build_option_name = ''Project Issues''',
'            )',
'union all',
'    select replace(initcap(replace(replace(f.column_name,''_ID'',null),''_'','' '')), chr(10),''<br>'') || '' Updated'' comment_text,',
'           null as affected_item,',
'           apex_escape.html(substr(f.old_value,1,255)) attribute_1,',
'           apex_escape.html(substr(f.new_value,1,255)) attribute_2,',
'           lower(f.changed_by) user_name,',
'           f.change_date comment_date,',
'           f.change_date as created,',
'           u.username as user_id,',
'           f.component_id as project_id',
'      from eba_proj_history f,',
'           eba_proj_status_users u',
'     where upper(f.changed_by) = upper(u.username)',
'       and f.change_date >= (trunc(sysdate) - 7)',
'union all',
'    select ''Action Item '' || replace(replace(initcap(replace(replace(f.column_name,''PROJECT_ID'',null),''_'','' '')), chr(10),''<br>''), ''Action '', null) || '' Updated'' comment_text,',
'           ai.action as affected_item,',
'           decode(f.column_name, ''PROJECT_ID'', null, ',
'           apex_escape.html(substr(f.old_value,1,255))) attribute_1,',
'           decode(f.column_name, ''PROJECT_ID'', null, ',
'           apex_escape.html(substr(f.new_value,1,255))) attribute_2,',
'           lower(f.changed_by) user_name,',
'           f.change_date comment_date,',
'           f.change_date as created,',
'           u.username as user_id,',
'           ai.project_id',
'      from eba_proj_history f,',
'           eba_proj_status_ais ai,',
'           eba_proj_status_users u',
'     where upper(f.changed_by) = upper(u.username)',
'       and f.table_name = ''STATUS_AIS''',
'       and f.component_id = ai.id',
'       and f.change_date >= (trunc(sysdate) - 7)',
'       and exists (select null',
'            from build_options',
'            where build_option_name = ''Project Action Items''',
'    )',
'union all',
'    select ''Milestone '' || replace(replace(initcap(replace(replace(f.column_name,''PROJECT_ID'',null),''_'','' '')), chr(10),''<br>''), ''Milestone '', null) || '' Updated'' comment_text,',
'           ms.milestone_name as affected_item,',
'           decode(f.column_name, ''PROJECT_ID'', null, ',
'           apex_escape.html(substr(f.old_value,1,255))) attribute_1,',
'           decode(f.column_name, ''PROJECT_ID'', null, ',
'           apex_escape.html(substr(f.new_value,1,255))) attribute_2,',
'           lower(f.changed_by) user_name,',
'           f.change_date comment_date,',
'           f.change_date as created,',
'           u.username as user_id,',
'           ms.project_id',
'      from eba_proj_history f,',
'           eba_proj_status_ms ms,',
'           eba_proj_status_users u',
'     where upper(f.changed_by) = upper(u.username)',
'       and f.table_name = ''STATUS_MS''',
'       and f.component_id = ms.id',
'       and f.change_date >= (trunc(sysdate) - 7)',
'       and exists (select null',
'            from build_options',
'            where build_option_name = ''Project Milestones''',
'    )',
'union all',
'    select ''Issue '' || replace(initcap(replace(replace(h.column_name,''PROJECT_ID'',null),''_'','' '')), chr(10),''<br>'') || '' Updated'' as comment_text,',
'           i.issue as affected_item,',
'           decode(h.column_name, ''PROJECT_ID'', null, ',
'           apex_escape.html(substr(h.old_value,1,255))) attribute_1,',
'           decode(h.column_name, ''PROJECT_ID'', null, ',
'           apex_escape.html(substr(h.new_value,1,255))) attribute_2,',
'           lower(h.changed_by) user_name,',
'           h.change_date comment_date,',
'           h.change_date as created,',
'           u.username as user_id,',
'           i.project_id',
'      from eba_proj_history h,',
'           eba_proj_status_issues i,',
'           eba_proj_status_users u',
'     where upper(h.changed_by) = upper(u.username)',
'       and h.table_name = ''STATUS_ISSUES''',
'       and h.component_id = i.id',
'       and h.change_date >= (trunc(sysdate) - 7)',
'       and exists (select null',
'            from build_options',
'            where build_option_name = ''Project Issues''',
'    );'))
);
wwv_flow_api.component_end;
end;
/
