prompt --application/deployment/install/install_eba_proj_nav_menu_view
begin
--   Manifest
--     INSTALL: INSTALL-eba_proj_nav_menu view
--   Manifest End
wwv_flow_api.component_begin (
 p_version_yyyy_mm_dd=>'2021.04.15'
,p_release=>'21.1.7'
,p_default_workspace_id=>9008156634332785
,p_default_application_id=>134
,p_default_id_offset=>172493832712964115
,p_default_owner=>'MISO'
);
wwv_flow_api.create_install_script(
 p_id=>wwv_flow_api.id(5463098661584302839)
,p_install_id=>wwv_flow_api.id(9012014618759672631)
,p_name=>'eba_proj_nav_menu view'
,p_sequence=>740
,p_script_type=>'INSTALL'
,p_script_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'CREATE OR REPLACE VIEW "EBA_PROJ_NAV_MENU" ("LVL", "LABEL", "TARGET", "IS_CURRENT_LIST_ENTRY", "IMAGE", "IMAGE_ATTRIBUTE", "IMAGE_ALT_ATTRIBUTE", "ATTRIBUTE1", "ATTRIBUTE2", "ATTRIBUTE3", "ATTRIBUTE4") AS ',
'  with constants as (',
'    select sys_context(''APEX$SESSION'',''APP_USER'') usr,',
'        v(''APP_ID'') app_id,',
'        sys_context(''APEX$SESSION'',''APP_SESSION'') app_session,',
'        v(''APP_PAGE_ID'') app_page_id,',
'        nvl( (  select preference_value',
'                from eba_proj_user_preferences pr',
'                where pr.username = sys_context(''APEX$SESSION'',''APP_USER'')',
'                    and pr.preference_name = ''NAVIGATION MENU'' ), ''OPEN'' ) show_projects',
'    from dual',
'),',
'prj as (',
'    select p.id,',
'        case when not exists ( select null',
'                                from eba_proj_status p2',
'                                where p2.id = p.parent_project_id ) then',
'                null',
'            else',
'                p.parent_project_id',
'            end as parent_project_id,',
'            p.project,',
'            p.cat_id',
'    from  eba_proj_status p,',
'        eba_proj_status_codes sc,',
'        constants c',
'    where sc.id = p.project_status',
'        and ( c.show_projects = ''ALL''',
'            or sc.is_closed_status = ''N''',
'        )',
'), people as (',
'    select distinct lower(u.username) project_owner',
'    from eba_proj_status p,',
'        eba_proj_user_ref rf,',
'        eba_proj_status_users u,',
'        eba_proj_roles r',
'    where rf.project_id = p.id',
'        and rf.user_id = u.id',
'        and rf.role_id = r.id',
'        and eba_proj_fw.is_edit_authorized( u.username, rf.project_id ) = ''Y''',
')',
'select l lvl,',
'    lb label,',
'    t target,',
'    ic is_current_list_entry,',
'    im image,',
'    null image_attribute,',
'    null image_alt_attribute,',
'    o0 attribute1,',
'    o1 attribute2,',
'    o2 attribute3,',
'    o3 attribute4',
'from (',
'select 1 l,',
'    ( select preference_value from eba_proj_preferences pr where pr.preference_name = ''CUSTOM_MENU'' ) lb,',
'    ( select preference_value from eba_proj_preferences pr where pr.preference_name = ''CUSTOM_MENU_URL'' ) t,',
'    ''NO'' ic,',
'    ( select preference_value from eba_proj_preferences pr where pr.preference_name = ''CUSTOM_MENU_ICON'' ) im,',
'    ''1'' o0,',
'    '''' o1,',
'    '''' o2,',
'    '''' o3',
'from dual',
'where exists ( select null from eba_proj_preferences pr where pr.preference_name = ''CUSTOM_MENU'' )',
'union all',
'select 1 l,',
'    ''Projects'' lb,',
'    ''f?p=''||c.app_id||'':64:''||c.app_session t,',
'    case when '':64:'' like ''%:''||c.app_page_id||'':%'' then ''YES''',
'        else ''NO''',
'    end as ic,',
'    case when exists ( select null from eba_proj_preferences pr where pr.preference_name = ''CUSTOM_MENU'' )',
'        and ''fa-home'' = ( select preference_value from eba_proj_preferences pr where pr.preference_name = ''CUSTOM_MENU_ICON'' ) then',
'            ''fa-archive''',
'        else ''fa-home''',
'    end as im,',
'    ''20'' o0,',
'    '''' o1,',
'    '''' o2,',
'    '''' o3',
'from constants c',
'union all',
'select level+1 l,',
'    substr(p.project,1,20) lb,',
'    ''f?p=''||c.app_id||'':200:''||c.app_session||'':::200:P200_ID:''||p.id t,',
'    case when '':33:52:99:130:194:'' like ''%:''||c.app_page_id||'':%'' then ''NO''',
'        else decode(NVL(v(''P200_ID''),0),p.id,''YES'',''NO'')',
'    end as ic,',
'    '''' im,',
'    ''30'' o0,',
'    case when level = 1 then p.project else',
'      (select p1.project from prj p1 where p1.id = p.parent_project_id) end as o1,',
'    case when level = 1 then ''1'' else ''2'' end as o2,',
'    case when level = 1 then null else upper(p.project) end as o3',
'from prj p,',
'    constants c',
'start with p.parent_project_id is null',
'connect by p.parent_project_id = prior p.id',
'union all',
'select 1 l,',
'    replace(eba_proj_fw.get_preference_value(''CAT_TITLE_PL''),''Preference does not exist'',''Categories'') lb,',
'    ''f?p=''||c.app_id||'':139:''||c.app_session||''::::P139_CATEGORY:'' t,',
'    decode(c.app_page_id,139,''YES'',''NO'') ic,',
'    ''fa-folder-o'' im,',
'    ''40'' o0,',
'    ''1'' o1,',
'    '''' o2,',
'    '''' o3',
'from constants c',
'union all',
'select 2 l,',
'    category lb,',
'    ''f?p=''||ct.app_id||'':139:''||ct.app_session||''::::P139_CATEGORY:''||c.id t,',
'    decode(ct.app_page_id,139,''YES'',''NO'') ic,',
'    '''' im,',
'    ''40'' o0,',
'    ''2'' o1,',
'    category o2,',
'    '''' o3',
'from eba_proj_status_cats c,',
'    constants ct',
'where exists (select 1 from prj x where x.cat_id = c.id)',
'union all',
'select 1 l,',
'    ''People'' lb,',
'    ''f?p=''||c.app_id||'':133:''||c.app_session||'':::133'' t,',
'    case when '':113:133:137:138:'' like ''%:''||c.app_page_id||'':%'' then ''YES'' else ''NO'' end as ic,',
'    ''fa-users'' im,',
'    ''70'' o0,',
'    ''1'' o1,',
'    '''' o2,',
'    '''' o3',
'from constants c',
'union all',
'select 1 l,',
'    ''My Dashboard'' lb,',
'    ''f?p=''||c.app_id||'':194:''||c.app_session t,',
'    case when '':194:212:213:215:217:'' like ''%:''||c.app_page_id||'':%'' then ''YES'' else ''NO'' end as ic,',
'    ''fa-dashboard'' im,',
'    ''39'' o0,',
'    ''1'' o1,',
'    '''' o2,',
'    '''' o3',
'from constants c',
'union all',
'select 1 l,',
'    ''Milestones'' lb,',
'    ''f?p=''||c.app_id||'':35:''||c.app_session||'':::35'' t,',
'    decode(c.app_page_id,35,''YES'',''NO'') ic,',
'    ''fa-calendar'' im,',
'    ''50'' o0,',
'    ''1'' o1,',
'    '''' o2,',
'    '''' ob3',
'from constants c',
'where exists ( select null',
'               from apex_application_build_options',
'               where application_id = c.app_id',
'                   and build_option_name = ''Project Milestones''',
'                   and build_option_status = ''Include''',
'             )',
'union all',
'select 2 l,',
'    x.period_name lb,',
'    ''f?p=''||c.app_id||'':35:''||c.app_session||'':::35:P35_QUARTER:''||x.period_name t,',
'    decode(c.app_page_id,35,''YES'',''NO'') ic,',
'    '''' im,',
'    ''50'' o0,',
'    ''2'' o1,',
'    to_char(x.lvl) o2,',
'    '''' o3',
'from (',
'        select rownum as lvl,',
'--               substr(period_name,1,2) || '' - '' || substr(period_name,3) as period_label,',
'               period_name',
'          from eba_proj_fy_periods',
'         where first_day >= localtimestamp',
'           and last_day <= localtimestamp + INTERVAL ''2'' YEAR',
'           and rownum <= 5',
'         order by first_day',
'     ) x,',
'    constants c',
'where exists ( select null',
'               from apex_application_build_options',
'               where application_id = c.app_id',
'                   and build_option_name = ''Project Milestones''',
'                   and build_option_status = ''Include''',
'             )',
'union all',
'select 1 l,',
'    ''Action Items'' lb,',
'    ''f?p=''||c.app_id||'':125:''||c.app_session||'':::125'' t,',
'    decode(c.app_page_id,125,''YES'',''NO'') ic,',
'    ''fa-calendar'' im,',
'    ''60'' o0,',
'    ''1'' o1,',
'    '''' o2,',
'    '''' o3',
'from constants c',
'where exists ( select null',
'               from apex_application_build_options',
'               where application_id = c.app_id',
'                   and build_option_name = ''Project Action Items''',
'                   and build_option_status = ''Include''',
'             )',
'union all',
'select 2 l,',
'    x.period_name lb,',
'    ''f?p=''||c.app_id||'':125:''||c.app_session||'':::125:P125_QUARTER:''||x.period_name t,',
'    decode(c.app_page_id,125,''YES'',''NO'') ic,',
'    '''' im,',
'    ''60'' o0,',
'    ''2'' o1,',
'    to_char(x.lvl) o2,',
'    '''' o3',
'from (',
'        select rownum as lvl,',
'--               substr(period_name,1,2) || '' - '' || substr(period_name,3) as period_label,',
'               period_name',
'          from eba_proj_fy_periods',
'         where first_day >= localtimestamp',
'           and last_day <= localtimestamp + INTERVAL ''2'' YEAR',
'           and rownum <= 5',
'         order by first_day',
'     ) x,',
'    constants c',
'where exists ( select null',
'               from apex_application_build_options',
'               where application_id = c.app_id',
'                   and build_option_name = ''Project Action Items''',
'                   and build_option_status = ''Include''',
'             )',
'union all',
'select 1 l,',
'    ''Timeline'' lb,',
'    ''f?p=''||c.app_id||'':10:''||c.app_session t,',
'    case when '':10:'' like ''%:''||c.app_page_id||'':%'' then ''YES'' else ''NO'' end as ic,',
'    ''fa-clock-o'' im,',
'    ''80'' o0,',
'    '''' o1,',
'    '''' o2,',
'    '''' o3',
'from constants c',
'union all',
'select 1 l,',
'    ''Reporting'' lb,',
'    ''f?p=''||c.app_id||'':136:''||c.app_session||'':::136'' t,',
'    case when '':1:4:5:8:9:13:14:17:19:21:22:26:29:30:45:46:49:50:51:59:61:63:68:72:''',
'            ||''88:95:98:111:114:117:118:126:132:136:158:177:214:216:219:''',
'        like ''%:''||c.app_page_id||'':%'' then ''YES'' else ''NO'' end as ic,',
'    ''fa-dashboard'' im,',
'    ''90'' o0,',
'    ''1'' o1,',
'    '''' o2,',
'    '''' o3',
'from constants c',
'union all',
'select 1 l,',
'    ''Administration'' lb,',
'    ''f?p=''||c.app_id||'':27:''||c.app_session||'':::136'' t,',
'    case when '':7:11:13:15:16:18:23:27:31:32:36:38:39:40:41:42:44:47:53:56:57:60:69:70:71:79''',
'            ||'':80:81:82:86:89:90:91:94:96:97:100:103:104:105:108:109:110:112:119''',
'            ||'':131:134:135:140:141:142:143:144:145:146:147:148:149:152''',
'            ||'':153:154:155:156:160:161:163:165:166:167:171:172:175:180:182:184:''',
'            ||'':196:197:203:205:206:207:208:220:''',
'        like ''%:''||c.app_page_id||'':%'' then ''YES'' else ''NO'' end as ic,',
'    ''fa-user-wrench'' im,',
'    ''999'' o0,',
'    ''1'' o1,',
'    '''' o2,',
'    '''' o3',
'from constants c',
'where 3 <= (select eba_proj_stat_ui.get_authorization_level(c.usr) from dual)',
')',
'/'))
);
wwv_flow_api.component_end;
end;
/
