prompt --application/deployment/install/install_templates_ddl
begin
--   Manifest
--     INSTALL: INSTALL-templates DDL
--   Manifest End
wwv_flow_api.component_begin (
 p_version_yyyy_mm_dd=>'2021.04.15'
,p_release=>'21.1.7'
,p_default_workspace_id=>9008156634332785
,p_default_application_id=>134
,p_default_id_offset=>172493832712964115
,p_default_owner=>'MISO'
);
wwv_flow_api.create_install_script(
 p_id=>wwv_flow_api.id(13596524908279670618)
,p_install_id=>wwv_flow_api.id(9012014618759672631)
,p_name=>'templates DDL'
,p_sequence=>260
,p_script_type=>'INSTALL'
,p_script_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'create table eba_proj_templates',
'(',
'    id                number,',
'    name              varchar2(255) not null,',
'    restrict_edits_yn varchar2(1) default ''N'' not null,',
'    row_version       number,',
'    --',
'    created           timestamp with local time zone,',
'    created_by        varchar2(255),',
'    updated           timestamp with local time zone,',
'    updated_by        varchar2(255),',
'    constraint eba_proj_templates_pk primary key (id)',
')',
'/',
'',
'create or replace trigger biu_eba_proj_templates',
'    before insert or update on eba_proj_templates',
'    for each row',
'begin',
'    if :new.id is null then',
'        :new.id := to_number(sys_guid(),''XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'');',
'    end if;',
'    if inserting then',
'        if :new.created is null then',
'            :new.created := localtimestamp;',
'        end if;',
'        if :new.created_by is null then',
'            :new.created_by := nvl(wwv_flow.g_user, user);',
'        end if;',
'        :new.row_version := 1;',
'    else',
'        :new.row_version := nvl(:old.row_version, 1) + 1;',
'    end if;',
'    :new.updated := localtimestamp;',
'    :new.updated_by := nvl(wwv_flow.g_user,user);',
'end;',
'/',
'',
'alter trigger biu_eba_proj_templates enable',
'/',
'',
'create table eba_proj_template_ms',
'(',
'    id                number,',
'    parent_milestone_id number,',
'    template_id       number                          not null,',
'    name              varchar2(255)                   not null,',
'    row_version       number,',
'    description       varchar2(4000),',
'    owner             varchar2(255),',
'    owner_role_id     number,',
'    start_date_offset number                          not null,',
'    due_date_offset   number                          not null,',
'    is_major_yn       varchar2(1),',
'    created           timestamp with local time zone,',
'    created_by        varchar2(255),',
'    updated           timestamp with local time zone,',
'    updated_by        varchar2(255),',
'    constraint eba_proj_templates_ms_pk primary key (id),',
'    constraint eba_proj_template_ms_tmpl_fk',
'        foreign key (template_id)',
'        references eba_proj_templates (id)',
'        on delete cascade,',
'    constraint eba_proj_template_ms_tmplms_fk',
'        foreign key (parent_milestone_id)',
'        references eba_proj_template_ms(id)',
'        on delete set null',
')',
'/',
'',
'create or replace trigger biu_eba_proj_template_ms',
'    before insert or update on eba_proj_template_ms',
'    for each row',
'begin',
'    if :new.id is null then',
'        :new.id := to_number(sys_guid(),''XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'');',
'    end if;',
'    if inserting then',
'        if :new.created is null then',
'            :new.created := localtimestamp;',
'        end if;',
'        if :new.created_by is null then',
'            :new.created_by := nvl(wwv_flow.g_user, user);',
'        end if;',
'        :new.row_version := 1;',
'    else',
'        :new.row_version := nvl(:old.row_version, 1) + 1;',
'    end if;',
'    :new.updated := localtimestamp;',
'    :new.updated_by := nvl(wwv_flow.g_user, user);',
'    update eba_proj_templates set updated = localtimestamp, updated_by = nvl(wwv_flow.g_user, user) where id = nvl(:new.template_id, :old.template_id);',
'end;',
'/',
'',
'alter trigger biu_eba_proj_template_ms enable',
'/',
'',
'create table eba_proj_template_ai',
'(',
'    id                   number,',
'    template_id          number                          not null,',
'    name                 varchar2(255)                   not null,',
'    row_version          number,',
'    description          varchar2(4000),',
'    owner                varchar2(255),',
'    owner_role_id        number,',
'    due_date_offset      number                          not null,',
'    type_id              number,',
'    milestone_id         number,',
'    link_url             varchar2(255),',
'    link_text            varchar2(255),',
'    created              timestamp with local time zone,',
'    created_by           varchar2(255),',
'    updated              timestamp with local time zone,',
'    updated_by           varchar2(255),',
'    inc_in_status_eml_yn varchar2(1)                     default ''Y'',',
'    constraint eba_proj_templates_ai_pk primary key (id),',
'    constraint eba_proj_template_ai_tmpl_fk',
'        foreign key (template_id)',
'        references eba_proj_templates (id)',
'        on delete cascade,',
'    constraint eba_proj_template_ai_ms_fk',
'        foreign key (milestone_id)',
'        references eba_proj_template_ms (id)',
'        on delete set null,',
'    constraint eba_proj_template_ai_type_fk',
'        foreign key (type_id)',
'        references eba_proj_status_ais_types (id)',
')',
'/',
'',
'create or replace trigger biu_eba_proj_template_ai',
'    before insert or update on eba_proj_template_ai',
'    for each row',
'begin',
'    if :new.id is null then',
'        :new.id := to_number(sys_guid(),''XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'');',
'    end if;',
'    if inserting then',
'        if :new.created is null then',
'            :new.created := localtimestamp;',
'        end if;',
'        if :new.created_by is null then',
'            :new.created_by := nvl(wwv_flow.g_user, user);',
'        end if;',
'        :new.row_version := 1;',
'    else',
'        :new.row_version := nvl(:old.row_version, 1) + 1;',
'    end if;',
'    :new.updated := localtimestamp;',
'    :new.updated_by := nvl(wwv_flow.g_user, user);',
'    update eba_proj_templates set updated = localtimestamp, updated_by = nvl(wwv_flow.g_user, user) where id = nvl(:new.template_id, :old.template_id);',
'end;',
'/',
'',
'alter trigger biu_eba_proj_template_ai enable',
'/',
'',
'alter table eba_proj_status$',
'add constraint eba_proj_status_temp_fk foreign key ( template_id )',
'    references eba_proj_templates(id) on delete set null;',
'/'))
);
wwv_flow_api.component_end;
end;
/
