prompt --application/deployment/install/upgrade_eba_proj_help_package_body
begin
--   Manifest
--     INSTALL: UPGRADE-eba_proj_help package body
--   Manifest End
wwv_flow_api.component_begin (
 p_version_yyyy_mm_dd=>'2021.04.15'
,p_release=>'21.1.7'
,p_default_workspace_id=>9008156634332785
,p_default_application_id=>134
,p_default_id_offset=>172493832712964115
,p_default_owner=>'MISO'
);
wwv_flow_api.create_install_script(
 p_id=>wwv_flow_api.id(1918802222842910876)
,p_install_id=>wwv_flow_api.id(9012014618759672631)
,p_name=>'eba_proj_help package body'
,p_sequence=>1210
,p_script_type=>'UPGRADE'
,p_script_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'create or replace package body eba_proj_help as',
'    function get_project_details_help_text(',
'        p_app_id in number',
'    ) return varchar2',
'    is',
'        l_help_text varchar2(32767);',
'    begin',
'        l_help_text := ''<p>This page allows project members with the right privileges to update the project''''s details, view (and/or manage) project members, and perform the following tasks:</p><ul>'';',
'',
'        if apex_util.get_build_option_status(',
'              p_application_id    => p_app_id,',
'              p_build_option_name => ''Project Action Items''',
'           ) = ''INCLUDE'' then',
'            l_help_text := l_help_text || ''<li>Add/Manage Action Items</li>'';',
'        end if;',
'',
'        if apex_util.get_build_option_status(',
'              p_application_id    => p_app_id,',
'              p_build_option_name => ''Project Attachments''',
'           ) = ''INCLUDE'' then',
'            l_help_text := l_help_text || ''<li>Add/Manage Attachments</li>'';',
'        end if;',
'',
'        if apex_util.get_build_option_status(',
'              p_application_id    => p_app_id,',
'              p_build_option_name => ''Project Code Names''',
'           ) = ''INCLUDE'' then',
'            l_help_text := l_help_text || ''<li>Assign a project "Code Name"</li>'';',
'        end if;',
'',
'        if apex_util.get_build_option_status(',
'              p_application_id    => p_app_id,',
'              p_build_option_name => ''Project Countries''',
'           ) = ''INCLUDE'' then',
'            l_help_text := l_help_text || ''<li>Add/Manage Countries</li>'';',
'        end if;',
'',
'        if apex_util.get_build_option_status(',
'              p_application_id    => p_app_id,',
'              p_build_option_name => ''Project Deal Types''',
'           ) = ''INCLUDE'' then',
'            l_help_text := l_help_text || ''<li>Assign a project "Deal Type"</li>'';',
'        end if;',
'',
'        if apex_util.get_build_option_status(',
'              p_application_id    => p_app_id,',
'              p_build_option_name => ''Project Issues''',
'           ) = ''INCLUDE'' then',
'            l_help_text := l_help_text || ''<li>Add/Manage Issues</li>'';',
'        end if;',
'',
'        if apex_util.get_build_option_status(',
'              p_application_id    => p_app_id,',
'              p_build_option_name => ''Project Links''',
'           ) = ''INCLUDE'' then',
'            l_help_text := l_help_text || ''<li>Add/Manage Links</li>'';',
'        end if;',
'',
'        if apex_util.get_build_option_status(',
'              p_application_id    => p_app_id,',
'              p_build_option_name => ''Project Milestones''',
'           ) = ''INCLUDE'' then',
'            l_help_text := l_help_text || ''<li>Add/Manage Milestones</li>'';',
'        end if;',
'',
'        if apex_util.get_build_option_status(',
'              p_application_id    => p_app_id,',
'              p_build_option_name => ''Project Resources''',
'           ) = ''INCLUDE'' then',
'            l_help_text := l_help_text || ''<li>Add/Manage Resources</li>'';',
'        end if;',
'',
'        if apex_util.get_build_option_status(',
'              p_application_id    => p_app_id,',
'              p_build_option_name => ''Project Sizes''',
'           ) = ''INCLUDE'' then',
'            l_help_text := l_help_text || ''<li>Assign a project "Size"</li>'';',
'        end if;',
'',
'        if apex_util.get_build_option_status(',
'              p_application_id    => p_app_id,',
'              p_build_option_name => ''Project Status Reports''',
'           ) = ''INCLUDE'' then',
'            l_help_text := l_help_text || ''<li>Add/Manage Status Reports</li>'';',
'        end if;',
'',
'        if apex_util.get_build_option_status(',
'              p_application_id    => p_app_id,',
'              p_build_option_name => ''Project Updates''',
'           ) = ''INCLUDE'' then',
'            l_help_text := l_help_text || ''<li>Add/Manage Updates</li>'';',
'        end if;',
'',
'        if apex_util.get_build_option_status(',
'              p_application_id    => p_app_id,',
'              p_build_option_name => ''Project User Involvement''',
'           ) = ''INCLUDE'' then',
'            l_help_text := l_help_text || ''<li>Track the involvement level of each project member</li>'';',
'        end if;',
'',
'        if apex_util.get_build_option_status(',
'              p_application_id    => p_app_id,',
'              p_build_option_name => ''Project Validations''',
'           ) = ''INCLUDE'' then',
'            l_help_text := l_help_text || ''<li>Validate the project and see previous validations</li>'';',
'        end if;',
'',
'        if apex_util.get_build_option_status(',
'              p_application_id    => p_app_id,',
'              p_build_option_name => ''Content complete "fish bowl"''',
'           ) = ''INCLUDE'' then',
'            l_help_text := l_help_text || ''<li>View the project''''s "completeness" level</li>'';',
'        end if;',
'',
'        if apex_util.get_build_option_status(',
'              p_application_id    => p_app_id,',
'              p_build_option_name => ''Merge''',
'           ) = ''INCLUDE'' then',
'            l_help_text := l_help_text || ''<li>Merge the project into another project as a child project</li>'';',
'        end if;',
'',
'        if apex_util.get_build_option_status(',
'              p_application_id    => p_app_id,',
'              p_build_option_name => ''Perma Link''',
'           ) = ''INCLUDE'' then',
'            l_help_text := l_help_text || ''<li>Display a "Permalink" (that can be copied and pasted into emails or instant messages for others to access the project)</li>'';',
'        end if;',
'',
'        l_help_text := l_help_text || ''</ul>'';',
'        return l_help_text;',
'    end get_project_details_help_text;',
'end eba_proj_help;',
'/',
'show errors'))
);
wwv_flow_api.component_end;
end;
/
