prompt --application/deployment/install/upgrade_eba_proj_stat_ui_body
begin
--   Manifest
--     INSTALL: UPGRADE-eba_proj_stat_ui body
--   Manifest End
wwv_flow_api.component_begin (
 p_version_yyyy_mm_dd=>'2021.04.15'
,p_release=>'21.1.7'
,p_default_workspace_id=>9008156634332785
,p_default_application_id=>134
,p_default_id_offset=>172493832712964115
,p_default_owner=>'MISO'
);
wwv_flow_api.create_install_script(
 p_id=>wwv_flow_api.id(6094282081217080924)
,p_install_id=>wwv_flow_api.id(9012014618759672631)
,p_name=>'eba_proj_stat_ui body'
,p_sequence=>1100
,p_script_type=>'UPGRADE'
,p_script_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'CREATE OR REPLACE PACKAGE BODY "EBA_PROJ_STAT_UI" as',
'    procedure print_styles2 is',
'    begin',
'        sys.htp.p(''<style type="text/css">',
'table.status_table {',
'    width: 100%;',
'    }',
'    table.status_table th {',
'        text-align: left;',
'        font: normal 12px/24px Arial, sans-serif;',
'        padding: 5px;',
'        border-bottom: 1px solid #EEE;',
'        white-space: nowrap;',
'        text-overflow: ellipsis;',
'        overflow: hidden;',
'        }',
'        table.status_table th a {',
'            color: #333;',
'            }',
'        table.status_table th.status_type {',
'            font: bold 14px/24px Arial, sans-serif;',
'            color: #000;',
'            padding: 5px;',
'            text-align: left;',
'            }',
'    table.status_table td {',
'        padding: 5px;',
'        border-bottom: 1px solid #EEE;',
'        width: 90%;',
'        }',
'    table.status_table span.status_bar {',
'        display: block;',
'        width: 100%;',
'        -webkit-border-radius: 6px;',
'        -moz-border-radius: 6px;',
'        border-radius: 6px;',
'        border: 1px solid #AAA;',
'        border: 1px solid rgba(0,0,0,.4);',
'        background: -webkit-gradient(linear, 0% 0%, 0% 100%, from(rgba(0,0,0,0)), to(rgba(0,0,0,.15))) #FFF;',
'        background-color: #FFF;',
'        font: bold 14px/24px Arial, sans-serif;',
'        -webkit-background-clip: padding-box;',
'        }',
'        table.status_table span.status_bar span {',
'            background: -webkit-gradient(linear, 0% 0%, 0% 100%, from(rgba(0,0,0,0)), to(rgba(0,0,0,.15))) #CCC;',
'            background-color: #CCC;',
'            display: block;',
'            height: 24px;',
'            -webkit-border-radius: 5px;',
'            -moz-border-radius: 5px;',
'            border-radius: 5px;',
'            }',
'        table.status_table td.status_red span.status_bar span {',
'            background: -webkit-gradient(linear, 0% 0%, 0% 100%, from(rgba(255,255,255,.15)), to(rgba(0,0,0,.25))) #E10;',
'            background-color: #E10;',
'            }',
'        table.status_table td.status_yellow span.status_bar span {',
'            background: -webkit-gradient(linear, 0% 0%, 0% 100%, from(rgba(255,255,255,.15)), to(rgba(0,0,0,.25))) #FD0;',
'            background-color: #FD0;',
'            }',
'        table.status_table td.status_green span.status_bar span {',
'            background: -webkit-gradient(linear, 0% 0%, 0% 100%, from(rgba(255,255,255,.15)), to(rgba(0,0,0,.25))) #0C0;',
'            background-color: #0C0;',
'            }',
'        table.status_table td.status_black span.status_bar span {',
'            background: -webkit-gradient(linear, 0% 0%, 0% 100%, from(rgba(255,255,255,.15)), to(rgba(0,0,0,.25))) #111;',
'            background-color: #111;',
'            }',
'    table.status_table span.status_bar strong {',
'        width: 100%;',
'        display: block;',
'        text-align: center;',
'        float: left;',
'        }',
'        table.status_table span.status_bar strong a {',
'            color: #000;',
'            text-decoration: none;',
'            display: block;',
'            text-shadow: 0 1px 0 rgba(255,255,255,.5);',
'            }',
'            table.status_table span.status_bar strong a:hover {',
'                background-color: rgba(0,0,0,.1);',
'                }',
'</style>'');',
'    end print_styles2;',
'',
'    procedure print_styles is',
'    begin',
'        sys.htp.p(''',
'<style>',
'   table.project_table td span.status_indicator,',
'       span.status_indicator  {',
'       display: block;',
'       min-width: 100px;',
'       max-width: 200px;',
'       text-align: center;',
'       padding: 0 5px;',
'       height: 12px;',
'       -moz-border-radius: 6px;',
'       -webkit-border-radius: 6px;',
'       -moz-border-radius: 6px;',
'       background-color: #CCC;',
'       border: 1px solid #AAA;',
'       border: 1px solid rgba(0,0,0,.25);',
'       font: bold 10px/12px arial, sans-serif',
'       }',
'       table.project_table td span.status_red, span.status_red{',
'           background-color: #EA0000;',
'           }',
'       table.project_table td span.status_yellow, span.status_yellow {',
'           background-color: #DD0;',
'           }',
'       table.project_table td span.status_green, span.status_green {',
'           background-color: #00BB00;',
'           }',
'       table.project_table td span.status_black, span.status_black {',
'           color: #CCC;',
'           background-color: #111;',
'           }',
'</style>'');',
'    end print_styles;',
'',
'    procedure create_rpt_by_status (',
'        p_app_id            in varchar2,',
'        p_app_session       in varchar2,',
'        p_image_prefix      in varchar2,',
'        p_target_page       in varchar2 default null,',
'        p_target_item       in varchar2 default null,',
'        p_target_page2      in varchar2 default null,',
'        p_target_item2      in varchar2 default null',
'        ) is',
'        c    pls_integer;',
'        tc   pls_integer;',
'        w    number;',
'        l_prog varchar2(30);',
'    begin',
'        begin',
'            print_styles2;',
'            select count(*) into tc from eba_proj_status;',
'            sys.htp.p(''<div class="status_container"><table class="status_table" border="0" cellspacing="0" cellpadding="0" summary="Projects by Status - Overall Counts">'');',
'            for c1 in',
'            (',
'                select',
'                    sc.ID,',
'                    sc.status_short_desc project_status,',
'                    col.color_code',
'                from',
'                    EBA_PROJ_STATUS_CODES sc,',
'                    eba_proj_color_codes col',
'                where',
'                    col.id = sc.color_code_id',
'                and',
'                    sc.is_active_yn = ''Y''',
'                order by',
'                    sc.display_sequence',
'            )',
'            loop',
'                select count(*) into c from eba_proj_status where project_status = c1.id;',
'                sys.htp.p(''<tr><th class="status_type" colspan="2" id="''||replace(c1.project_status,'' '',''_'')||''">''||c1.project_status||''</th>'');',
'                begin w := round((c*100)/tc); exception when others then w := 0; end;',
'                sys.htp.p(''<td headers="''||replace(c1.project_status,'' '',''_'')||''"><span class="status_bar"><strong><a href="f?p=''||',
'                   p_app_id||'':''||',
'                   p_target_page2||'':''||',
'                   p_app_session||'':::''||',
'                   p_target_page2||'',RIR,RP:''||',
'                   p_target_item2||'':''||',
'                   c1.project_status||''">''||',
'                   trim(to_char(c,''999G999G999G990''))||''</a></strong><span style="width: ''||w||''%;''',
'                        ||'' background-color: ''||c1.color_code||'';"></span></span></td>'');',
'                sys.htp.p(''<td headers="''||replace(c1.project_status,'' '',''_'')||''"><a href="f?p=''||',
'                   p_app_id||'':''||',
'                   p_target_page||'':''||',
'                   p_app_session||'':::''||',
'                   p_target_page||'',RIR,RP:''||',
'                   p_target_item||'':''||',
'                   c1.id||''">''||',
'                   ''<img src="''||p_image_prefix||''htmldb/icons/pt_page.png" alt="create report" title="create report"/>''||',
'                   ''</a></td>'');',
'            ',
'                sys.htp.p(''</tr>'');',
'            end loop;',
'            sys.htp.p(''</table></div>'');',
'        exception when others then',
'            sys.htp.p(''progress=''||l_prog||'' ''||sqlerrm);',
'        end;',
'    end create_rpt_by_status;',
'',
'    procedure top_status_by_code2 (',
'        p_max_rows          in number default 6,',
'        p_app_id            in varchar2,',
'        p_app_session       in varchar2,',
'        p_image_prefix      in varchar2,',
'        p_target_page       in varchar2 default null,',
'        p_target_item       in varchar2 default null,',
'        p_target_item2      in varchar2 default null)',
'    is',
'       l_empty_status       wwv_flow_global.vc_arr2;',
'       l_count              wwv_flow_global.n_arr;',
'       l_status             wwv_flow_global.vc_arr2;',
'       l_status_desc        wwv_flow_global.vc_arr2;',
'       cw                   pls_integer := 150; -- chart width',
'       c                    pls_integer := 0;',
'       w                    pls_integer := 0;',
'       l_max_count          pls_integer := 0;',
'       l_url                varchar2(4000);',
'    begin',
'        print_styles2;',
'        cw := 100;',
'        sys.htp.p(''<div class="status_container"><table class="status_table" border="0" cellspacing="0" cellpadding="0" summary="Projects by Status - Status Counts by Category">'');',
'        for c1 in (select cat_id, project_status, count(*) c from eba_proj_status group by cat_id, project_status order by 3 desc) loop',
'            l_max_count := c1.c;',
'            exit;',
'        end loop;',
'        ',
'        if l_max_count != 0 then',
'        ',
'            for c0 in (select sc.id,',
'                              sc.status_short_desc ,',
'                              col.color_code',
'                        from EBA_PROJ_STATUS_CODES sc,',
'                            eba_proj_color_codes col',
'                        where col.id = sc.color_code_id',
'                        order by sc.display_sequence) loop',
'                c := 0;',
'                l_status := l_empty_status;',
'                w := 0;',
'            ',
'                sys.htp.p(''<tr><th class="status_type" colspan="2" id="''||replace(c0.status_short_desc,'' '',''_'')||''">''||apex_escape.html(c0.status_short_desc)||''</th></tr>'');',
'                for c1 in (',
'                    select sc.CATEGORY status,',
'                           sc.CATEGORY status_short_desc,',
'                           count(*) c',
'                    from eba_proj_status s,',
'                         eba_proj_status_codes c,',
'                         EBA_PROJ_STATUS_CATS sc',
'                    where c.id = s.project_status and c.id = c0.id and sc.id = s.cat_id',
'                    group by sc.CATEGORY',
'                    having count(*) > 0',
'                    order by 3 desc',
'                ) loop',
'                   c := c + 1;',
'                   l_count(c) := c1.c;',
'                   l_status(c) := c1.status;',
'                   l_status_desc(c) := c1.status_short_desc;',
'                   if c = nvl(p_max_rows,6) then',
'                      exit;',
'                   end if;',
'                end loop;',
'                if c > 0 then',
'                    for i in 1..l_status.count loop',
'                       begin w := round(l_count(i)/l_max_count*cw); exception when others then w := 0; end;',
'                       l_url := ''f?p=''||',
'                           p_app_id||'':''||',
'                           p_target_page||'':''||',
'                           p_app_session||'':::''||',
'                           p_target_page||'',RP,RIR:''||',
'                           p_target_item||'',''||',
'                           p_target_item2||'':''||',
'                           l_status_desc(i)||'',''||',
'                           apex_escape.html( c0.status_short_desc);',
'                       sys.htp.p(''<th id="''||l_status_desc(i)||''"><a href="''||l_url||''">'');',
'                       sys.htp.prn(apex_escape.html(l_status_desc(i)));',
'                       sys.htp.p(''</a></th>'');',
'                       sys.htp.p(''<td headers="''||replace(l_status_desc(i),'' '',''_'')||'' ''||replace(c0.status_short_desc,'' '',''_'')||''"><span class="status_bar"><strong><a href="''||l_url||''">''||',
'                           trim(to_char(l_count(i),''999G999G999G990''))||',
'                           ''</a></strong><span style="width: ''||w||',
'                           ''%; background-color: ''||c0.color_code||'';"></span></span></td></tr>'');',
'                    end loop;',
'            ',
'                end if;',
'            end loop;',
'            sys.htp.p(''</table></div>'');',
'        ',
'        end if;',
'    end top_status_by_code2;',
'',
'    function project_report_by_cat ( p_category_id in number ) return varchar2 is',
'        cursor prj_csr is',
'            select c.status_short_desc,',
'                col.color_code,',
'                count(*) cnt',
'            from EBA_PROJ_STATUS s,',
'                eba_proj_status_codes c,',
'                eba_proj_color_codes col',
'            where c.id = s.PROJECT_STATUS',
'                and col.id = c.color_code_id',
'                and ((p_category_id is null and s.cat_id is null)',
'                    or s.cat_id = p_category_id )',
'            group by c.status_short_desc,',
'                col.color_code, c.is_active_yn, c.display_sequence',
'            having count(*) > 0',
'            order by c.is_active_yn desc, c.display_sequence;',
'        prj_rec prj_csr%ROWTYPE;',
'        l_maxcnt number;',
'        l_catname varchar2(500) := '''';',
'        l_table varchar2(2000) := ''<table class="status_table" border="0" cellspacing="0" cellpadding="0" style="width: 400px"><tr><td><span class="cumulative_status_bar">'';',
'    begin',
'        select max(count_of_Projects) into l_maxcnt',
'        from (  select CAT_ID, count(*) count_of_projects',
'                from EBA_PROJ_STATUS group by CAT_ID);',
'        if l_maxcnt = 0 then',
'            l_table := '''';',
'        else',
'            begin',
'                select category into l_catname',
'                from eba_proj_status_cats',
'                where id = p_category_id;',
'            exception when no_data_found then',
'                l_catname := '''';',
'            end;',
'            for prj_rec in prj_csr loop',
'                l_table := l_table',
'                    ||''<span class="status_bar" style="width: ''||round(100*(prj_rec.cnt/l_maxcnt),2)||''%;''',
'                    ||''background-color: ''||prj_rec.color_code||'';">''',
'                    ||''<strong><a href="''||''f?p=''||v(''APP_ID'')||'':1:''||v(''APP_SESSION'')',
'                    ||''::NO:1,RIR:IR_CATEGORY,IRC_STATUS:''||l_catname',
'                    ||'',''||prj_rec.status_short_desc||''">''||prj_rec.cnt||''</a></strong></span>'';',
'            end loop;',
'            l_table := l_table || ''</span></td></tr></table>'';',
'        end if;',
'        return l_table;',
'    end project_report_by_cat;',
'',
'    function project_report_by_owner( p_owner in varchar2 ) return varchar2 is',
'        cursor prj_csr is',
'            select c.status_short_desc,',
'                col.color_code,',
'                count(*) cnt',
'            from EBA_PROJ_STATUS s,',
'                eba_proj_status_codes c,',
'                eba_proj_color_codes col',
'            where c.id = s.PROJECT_STATUS',
'                and col.id = c.color_code_id',
'                and (',
'                    (   p_owner is null',
'                        and not exists (select null',
'                                        from eba_proj_user_ref rf,',
'                                            eba_proj_status_users u',
'                                        where rf.project_id = s.id',
'                                            and rf.user_id = u.id',
'                                            and eba_proj_fw.is_edit_authorized( u.username, rf.project_id ) = ''Y'')',
'                    ) or (p_owner is not null',
'                        and exists (select null',
'                                    from eba_proj_user_ref rf,',
'                                        eba_proj_status_users u',
'                                    where rf.project_id = s.id',
'                                        and rf.user_id = u.id',
'                                        and eba_proj_fw.is_edit_authorized( u.username, rf.project_id ) = ''Y''',
'                                        and lower(u.username) = lower(p_owner))',
'                    )',
'                )',
'            group by c.status_short_desc,',
'                col.color_code, c.is_active_yn, c.display_sequence',
'            having count(*) > 0',
'            order by c.is_active_yn desc, c.display_sequence;',
'        prj_rec prj_csr%ROWTYPE;',
'        l_maxcnt number;',
'        l_table varchar2(2000) := ''<table class="status_table" border="0" cellspacing="0" cellpadding="0" style="width: 400px"><tr><td><span class="cumulative_status_bar">'';',
'    begin',
'        select max(cc) into l_maxcnt',
'        from (  select lower(u.username) project_owner, count(*) cc',
'                from eba_proj_status p,',
'                    eba_proj_user_ref rf,',
'                    eba_proj_status_users u',
'                where p.id = rf.project_id',
'                    and rf.user_id = u.id',
'                    and eba_proj_fw.is_edit_authorized( u.username, rf.project_id ) = ''Y''',
'                group by lower(u.username)',
'            );',
'        if l_maxcnt = 0 then',
'            l_table := '''';',
'        else',
'            for prj_rec in prj_csr loop',
'                l_table := l_table',
'                    ||''<span class="status_bar" style="width: ''||round(100*(prj_rec.cnt/l_maxcnt),2)||''%;''',
'                    ||''background-color: ''||prj_rec.color_code||'';">''',
'                    ||''<strong><a href="''||''f?p=''||v(''APP_ID'')||'':1:''||v(''APP_SESSION'')',
'                    ||''::NO:1,RIR:IRC_OWNER,IR_STATUS:''||p_owner',
'                    ||'',''||prj_rec.status_short_desc||''">''||prj_rec.cnt||''</a></strong></span>'';',
'            end loop;',
'            l_table := l_table || ''</span></td></tr></table>'';',
'        end if;',
'        return l_table;',
'    end project_report_by_owner;',
'',
'    function is_project_open ( p_project_id in number ) return number is',
'        cursor chl_csr is',
'            select id',
'            from eba_proj_status',
'            where parent_project_id = p_project_id;',
'        l_chl chl_csr%ROWTYPE;',
'        l_open number := 0;',
'        l_cnt number;',
'    begin',
'        for l_chl in chl_csr loop',
'            l_open := is_project_open( l_chl.id );',
'            exit when l_open > 0;',
'        end loop;',
'        if l_open = 0 then',
'            select count(*) into l_cnt',
'            from eba_proj_status s',
'            where s.id = p_project_id',
'                and s.project_status not in ( select id',
'                                              from eba_proj_status_codes',
'                                              where is_closed_status = ''Y''',
'                            );',
'            if l_cnt > 0 then',
'                l_open := 1;',
'            end if;',
'        end if;',
'        return l_open;',
'    end is_project_open;',
'    ',
'    -------------------------------------------------------------------------',
'    -- Gets the current user''s authorization level. Depends on the following:',
'    --  * If access control is currently disabled, returns highest level of 3.',
'    --  * If access control is enabled, but user is not in list, returns 0',
'    --  * If access control is enabled and user is in list, returns their',
'    --    access level.',
'    -------------------------------------------------------------------------',
'    function get_authorization_level ( p_username varchar2) return number is',
'        l_access_level_id       eba_proj_status_users.access_level_id%type := 0;  -- default to lowest privilege.',
'        l_account_locked        eba_proj_status_users.account_locked%type;',
'    begin',
'        -- If the user isn''t authenticated, they have no privilege.',
'        if not apex_authentication.is_authenticated then',
'            return 0;',
'        end if;',
'        -- If access control is disabled, default to highest privilege',
'        if eba_proj_fw.get_preference_value(''ACCESS_CONTROL_ENABLED'') = ''N'' then',
'            return 4;',
'        else',
'            -- Query for user''s access level, throws no_data_found if no user',
'            select',
'                access_level_id,',
'                account_locked',
'            into l_access_level_id,',
'                l_account_locked',
'            from eba_proj_status_users',
'            where upper(username) = p_username;',
'            -- Check if user''s account is locked, return 0 (no privilege), otherwise stick',
'            -- with their level.',
'            if l_account_locked = ''Y'' then',
'                return 0;',
'            end if;',
'            -- Overwrite user access level 1 with access level 2 if access control scope is PUBLIC_CONTRIBUTE',
'            if l_access_level_id = 1 and eba_proj_fw.get_preference_value(''ACCESS_CONTROL_SCOPE'') = ''PUBLIC_CONTRIBUTE'' then',
'                return 2;',
'            end if;',
'        end if;',
'        return l_access_level_id;',
'    exception',
'        when no_data_found then',
'            -- If no user exists with passed username, do a final check if reader access is set to any authenticated user',
'            if eba_proj_fw.get_preference_value(''ACCESS_CONTROL_SCOPE'') = ''PUBLIC_CONTRIBUTE'' then',
'                return 2;',
'            elsif eba_proj_fw.get_preference_value(''ACCESS_CONTROL_SCOPE'') = ''PUBLIC_READONLY'' then',
'                return 1;',
'            else',
'                return 0;',
'            end if;',
'    end get_authorization_level;',
'',
'    function get_project_report_columns',
'    (',
'      p_status   in     number   default 0,',
'      p_category in     number   default 0,',
'      p_owner    in     varchar2 default null,',
'      p_search   in     varchar2 default null',
'    ) return varchar2',
'    is',
'        l_irr_cols   varchar2(1000);',
'    begin',
'        l_irr_cols := ''IRIN_OPEN_CLOSED'';',
'        if nvl(p_category,0) > 0 then',
'            l_irr_cols := l_irr_cols || '',IR_CATEGORY'';',
'        end if;',
'        if nvl(p_status,0) > 0 then',
'            l_irr_cols := l_irr_cols || '',IR_STATUS'';',
'        end if;',
'        if nvl(p_owner,''0'') != ''0'' then',
'            l_irr_cols := l_irr_cols || '',IRC_OWNER'';',
'        end if;',
'        if p_search is not null then',
'            l_irr_cols := l_irr_cols || '',IRC_PROJECT'';',
'        end if;',
'        return l_irr_cols;',
'    end get_project_report_columns;',
'',
'    function get_project_report_values',
'    (',
'      p_status   in     number   default 0,',
'      p_category in     number   default 0,',
'      p_owner    in     varchar2 default null,',
'      p_search   in     varchar2 default null',
'    ) return varchar2',
'    is',
'        l_status     varchar2(200);',
'        l_category   varchar2(200);',
'        l_irr_vals   varchar2(1000);',
'    begin',
'        if nvl(p_status,0) > 0 then',
'            select status_short_desc into l_status from eba_proj_status_codes where id = p_status;',
'        end if;',
'        if nvl(p_category,0) > 0 then',
'            select category into l_category from eba_proj_status_cats where id = p_category;',
'        end if;',
'        l_irr_vals := ''\Open,Closed\'';',
'        if nvl(p_category,0) > 0 then',
'            l_irr_vals := l_irr_vals || '','' || l_category;',
'        end if;',
'        if nvl(p_status,0) > 0 then',
'            l_irr_vals := l_irr_vals || '','' || l_status;',
'        end if;',
'        if nvl(p_owner,''0'') != ''0'' then',
'            l_irr_vals := l_irr_vals || '','' || p_owner;',
'        end if;',
'        if p_search is not null then',
'            l_irr_vals := l_irr_vals || '','' || p_search;',
'        end if;',
'        return l_irr_vals;',
'    end get_project_report_values;',
'end eba_proj_stat_ui;',
'/',
'',
''))
);
wwv_flow_api.create_install_object(
 p_id=>wwv_flow_api.id(6964823282480123826)
,p_script_id=>wwv_flow_api.id(6094282081217080924)
,p_object_owner=>'#OWNER#'
,p_object_type=>'PACKAGE BODY'
,p_object_name=>'EBA_PROJ_STAT_UI'
,p_last_updated_on=>to_date('20141219062054','YYYYMMDDHH24MISS')
,p_created_on=>to_date('20141219062054','YYYYMMDDHH24MISS')
);
wwv_flow_api.component_end;
end;
/
